plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = '0.16.1'
group = 'uy.santipdr.siege'
base { archivesName = 'siege-menu' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs { client { workingDirectory project.file('run'); property 'forge.logging.console.level', 'debug'; mods { siege { source sourceSets.main } } } }
}
repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.20.1-47.4.0' }
tasks.named('processResources', ProcessResources).configure {
    var props = [version: project.version]
    inputs.properties props
    filesMatching(['META-INF/mods.toml']) { expand props + [project: project] }
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

tasks.register('reportBuildTools') {
    doLast {
        println 'SIEGE_FORGEGRADLE=' + plugins.getPlugin('net.minecraftforge.gradle').class.protectionDomain.codeSource.location
    }
}
