package uy.santipdr.siege.client;

import java.util.List;

/** Canonical immutable Intel records, independent of screens. Original lore preserved. */
final class IntelData {
    static final List<IntelEntry> FILES = List.of(
            file("HU-001", "INFANTRY", "UNIT", 1, "100", "infantry",
                    "Sin registro confirmado", "FN SCAR + armadura táctica", "Esqueleto / Pillager", "ACTIVO",
                    "La primera unidad que suele aparecer durante los primeros días de una operación. Aunque es la tropa más débil, su inteligencia artificial le permite compartir información, formar grupos y crear estrategias entre varios Infantries. Las apariencias registradas incluyen esqueletos y Pillagers, siempre equipados para combate directo.",
                    "No subestimar una formación numerosa. Separar al grupo, romper su coordinación y eliminar primero a las unidades que estén cubriendo el avance.",
                    "No confirmed record", "FN SCAR + tactical armour", "Skeleton / Pillager", "ACTIVE",
                    "Usually the first unit encountered during the opening days of an operation. Although it is the weakest troop, its artificial intelligence lets several Infantries share information, form groups and coordinate tactics. Recorded appearances include Skeleton and Pillager bodies, always prepared for direct combat.",
                    "Do not underestimate a large formation. Split the group, disrupt its coordination and eliminate the units covering the advance first."),
            file("HU-002", "SHIELDER", "UNIT", 2, "150", "shielder",
                    "Sin registro confirmado", "Escopeta + dos escudos", "Emboscador", "ACTIVO",
                    "Unidad semipeligrosa especializada en emboscadas y ataques por la espalda. Dos o más Shielders pueden planificar una encerrona coordinada. Su escopeta aumenta drásticamente el daño a corta distancia y los dos escudos le permiten bloquear prácticamente cualquier ataque frontal.",
                    "Evitar el cuerpo a cuerpo y no desperdiciar munición contra los escudos. Forzar un giro, atacar desde los flancos y mantener distancia de la escopeta.",
                    "No confirmed record", "Shotgun + two shields", "Ambusher", "ACTIVE",
                    "A semi-dangerous unit specialised in ambushes and attacks from behind. Two or more Shielders can coordinate a trap. Its shotgun becomes dramatically more dangerous at close range, while the two shields can block almost any frontal attack.",
                    "Avoid close combat and do not waste ammunition on the shields. Force it to turn, attack from the flanks and stay outside shotgun range."),
            file("SOP-001", "SABOTEUR", "UNIT", 4, "120", "saboteur",
                    "Sin registro confirmado", "Dos pistolas + C4 + sabotaje electrónico", "C4 normal / C4 nuclear", "HOSTIL",
                    "Una de las unidades más peligrosas para cualquier asentamiento. Puede infiltrarse en invisibilidad, aparecer cuando ya está demasiado cerca y colocar cargas C4 sobre estructuras o directamente sobre un jugador. Su dispositivo de sabotaje también neutraliza torretas Sentinel y otros aparatos electrónicos.",
                    "Tratar toda anomalía electrónica como una infiltración. Localizarlo antes de que coloque cargas y evacuar inmediatamente cualquier zona marcada con C4.",
                    "No confirmed record", "Dual pistols + C4 + electronic sabotage", "Standard C4 / nuclear C4", "HOSTILE",
                    "One of the most dangerous units for any settlement. It can infiltrate while invisible, reveal itself only at very close range and attach C4 to structures or directly to a player. Its sabotage device can also disable Sentinel turrets and other electronics.",
                    "Treat every electronic anomaly as an infiltration. Locate it before charges are planted and evacuate any area marked with C4 immediately."),
            file("SOP-002", "STALKER", "UNIT", 3, "100", "stalker",
                    "Sin registro confirmado", "Rifle subsónico + panel de camuflaje + GPS", "Escuadras de infiltración", "HOSTIL",
                    "Unidad espía que entra al área mediante una explosión de humo y desactiva su camuflaje al iniciar el ataque. Los Stalkers operan en grupos, observan bases para reunir información y pueden colocar discretamente un rastreador GPS en su objetivo sin que este lo note.",
                    "Vigilar cada nube de humo repentina. Después del contacto, revisar el equipo en busca de rastreadores y asumir que la posición de la base pudo quedar comprometida.",
                    "No confirmed record", "Subsonic rifle + camouflage panel + GPS", "Infiltration squads", "HOSTILE",
                    "A spy unit that enters the area through a smoke burst and disables its camouflage when the attack begins. Stalkers operate in groups, observe bases to gather intelligence and can discreetly plant a GPS tracker on a target without being noticed.",
                    "Watch every sudden smoke cloud. After contact, inspect equipment for trackers and assume the base position may have been compromised."),
            file("MECH-001", "NATZUKA", "UNIT", 3, "105", "natzuka",
                    "Sin registro confirmado", "Armas de fuego + carga suicida explosiva", "Cuadrúpedo de bajo costo", "ACTIVO",
                    "Unidad mecánica cuadrúpeda diseñada para atravesar terrenos difíciles. Su función principal es el combate directo con armas de fuego; si la amenaza persiste, puede ejecutar una carga suicida explosiva. Su bajo costo y fabricación sencilla permiten despliegues masivos.",
                    "Destruirla a distancia y evitar espacios cerrados. Una Natzuka aislada puede ser reemplazada rápidamente por una oleada completa.",
                    "No confirmed record", "Firearms + suicidal explosive charge", "Low-cost quadruped", "ACTIVE",
                    "A quadruped mechanical unit designed to cross difficult terrain. Its primary role is direct combat with firearms; if the threat persists, it can perform a suicidal explosive charge. Low cost and simple manufacturing allow mass deployment.",
                    "Destroy it at range and avoid confined spaces. A single Natzuka can quickly be replaced by an entire wave."),
            file("HU-003", "SNIPER", "UNIT", 4, "150", "sniper",
                    "República de Nusia", "Rifle de precisión + radar + radio", "Unidad de retaguardia", "HOSTIL",
                    "Francotirador nusiano equipado para combate de largo alcance. Busca lentamente un objetivo, se agacha y lo sigue durante varios segundos antes de disparar un proyectil rápido y potente. Un láser rojo advierte el disparo. Si su posición queda expuesta, cambia de lugar y también intenta cubrirse contra otros francotiradores.",
                    "Romper la línea de visión en cuanto aparezca el láser. Avanzar bajo cobertura y presionarlo para impedir que vuelva a establecer una posición estable.",
                    "Republic of Nusia", "Precision rifle + radar + radio", "Rear-line unit", "HOSTILE",
                    "A Nusian sniper equipped for long-range combat. It slowly searches for a target, crouches and tracks it for several seconds before firing a fast, powerful projectile. A red laser warns of the shot. If exposed, it relocates and seeks cover against opposing snipers.",
                    "Break line of sight as soon as the laser appears. Advance under cover and keep pressure on it so it cannot establish another stable position."),
            file("HU-004", "GRENADIER", "UNIT", 4, "350", "grenadier",
                    "República de Nusia", "Lanzagranadas multifunción + visión nocturna", "Gas / explosivo", "HOSTIL",
                    "Unidad nusiana de retaguardia que analiza la situación antes de decidir cuándo atacar. Dispara gas lacrimógeno para cegar y ralentizar, y cambia a granadas reales cuando necesita defenderse. Puede teletransportarse mediante bombas de humo y ejecutar disparos acrobáticos con Stylish Battle Ranks que triplican el daño.",
                    "Separarse para reducir el efecto del gas, abandonar inmediatamente la nube y evitar trayectorias previsibles que faciliten un disparo acrobático.",
                    "Republic of Nusia", "Multifunction launcher + night vision", "Gas / explosive", "HOSTILE",
                    "A Nusian rear-line unit that analyses the situation before choosing when to attack. It fires tear gas to blind and slow targets, switching to live grenades for defence. It can teleport through smoke bombs and perform Stylish Battle Rank trick shots that triple damage.",
                    "Spread out to limit the gas, leave the cloud immediately and avoid predictable movement that enables an acrobatic shot."),
            file("HU-005", "GUNNER", "UNIT", 5, "600", "gunner",
                    "República de Nusia", "LMG + mochila pesada de munición", "Tanque de unidad común", "HOSTIL",
                    "El mayor tanque entre las unidades comunes de Nusia. Avanza lentamente con casco, máscara de gas y una gran reserva de munición. Al localizar un objetivo se posiciona, permanece quieto y dispara ráfagas extremadamente rápidas durante doce a veinte segundos, suficientes para derribar a un jugador en menos de diez.",
                    "No intentar esquivar las balas en campo abierto. Usar cobertura sólida, esperar el final de la ráfaga y atacar durante su reposicionamiento.",
                    "Republic of Nusia", "LMG + heavy ammunition pack", "Common-unit tank", "HOSTILE",
                    "The heaviest tank among Nusia's common units. It advances slowly with a helmet, gas mask and a large ammunition reserve. After acquiring a target it anchors itself and fires extremely fast bursts for twelve to twenty seconds, enough to down a player in under ten.",
                    "Do not attempt to dodge in open ground. Use solid cover, wait for the burst to end and attack during relocation."),
            file("HU-006", "JETPACKER", "UNIT", 4, "150", "jetpacker",
                    "Sin registro confirmado", "Jetpack + RPG + cámara binocular", "Aéreo / terrestre", "HOSTIL",
                    "Unidad explosiva extremadamente rápida que usa un Jetpack para alcanzar velocidades sónicas, abrumar al objetivo y lanzar misiles desde una posición calculada. Sus proyectiles no son teledirigidos. Si falla, activa el modo terrestre del dispositivo, obteniendo supervelocidad y supersalto sobre tierra y montañas. Un rastro amarillo revela su desplazamiento.",
                    "Seguir el rastro amarillo, dispersarse antes de la descarga y cambiar de dirección después del lanzamiento. Aprovechar que los misiles no corrigen su trayectoria.",
                    "No confirmed record", "Jetpack + RPG + binocular camera", "Airborne / ground", "HOSTILE",
                    "An extremely fast explosive unit that uses a jetpack to reach sonic speed, overwhelm its target and rain missiles from a calculated position. Its projectiles are not guided. If it misses, the device enters ground mode, granting super-speed and super-jump across land and mountains. A yellow trail reveals its movement.",
                    "Track the yellow trail, spread out before the barrage and change direction after launch. Exploit the fact that its missiles cannot correct course."),
            file("HU-007", "PATRIOT", "UNIT", 4, "350", "patriot",
                    "República de Nusia", "Fusil militar — datos incompletos", "Información insuficiente", "ARCHIVO INCOMPLETO",
                    "Expediente parcialmente censurado. La bandera recuperada y el registro corregido confirman su pertenencia a la República de Nusia. No existe información verificada suficiente sobre sus capacidades especiales, patrón de despliegue o función exacta dentro de las fuerzas nusianas.",
                    "No completar los vacíos con suposiciones. Tratarlo como hostil hasta recuperar datos operativos confirmados.",
                    "Republic of Nusia", "Military rifle — incomplete data", "Insufficient information", "INCOMPLETE FILE",
                    "Partially redacted dossier. The recovered flag and corrected record confirm allegiance to the Republic of Nusia. There is not enough verified information about special capabilities, deployment pattern or exact role within Nusian forces.",
                    "Do not fill missing information with assumptions. Treat it as hostile until confirmed operational data is recovered."),
            file("ADV-001", "SPECIALIST", "ADVANCED", 5, "500", "specialist",
                    "República de Nusia", "C4 + bombas nucleares + teletransportación", "Planificador / líder de escuadra", "HOSTIL",
                    "Maestro de operaciones, planificación y estrategia. Se infiltra en invisibilidad y, si el jugador está dentro de una base, rodea la estructura con C4 antes de detonarla de una vez. Puede sellar pozos con capas de obsidiana y rodear la salida con explosivos nucleares. En grupos grandes asume el liderazgo, crea estrategias y distribuye órdenes. Posee teletransportación, autoconsciencia e IA cercana al nivel de jugadores PVP UHC.",
                    "No permanecer dentro de estructuras ni pozos después de detectarlo. Romper el grupo antes de que asuma el mando y cambiar constantemente de plan.",
                    "Republic of Nusia", "C4 + nuclear bombs + teleportation", "Planner / squad leader", "HOSTILE",
                    "Master of operations, planning and strategy. It infiltrates invisibly and, when a player is inside a base, surrounds the structure with C4 before detonating everything at once. It can seal pits with layered obsidian and ring the exit with nuclear explosives. In large groups it assumes command, creates strategies and issues orders. It possesses teleportation, self-awareness and AI approaching UHC PVP players.",
                    "Do not remain inside structures or pits after detection. Break the group before it assumes command and change tactics constantly."),
            file("ADV-002", "DEMOMAN", "ADVANCED", 4, "NAN", "demoman",
                    "República de Nusia", "Rifle de asalto + dinamita corporal", "Kamikaze avanzado", "HOSTIL",
                    "Maestro del suicidio definitivo y enemigo silencioso. Porta un rifle de asalto y una cantidad extrema de dinamita adherida al cuerpo. Tarda más en detonar que una unidad Kamikaze común, pero la explosión resultante es considerablemente mayor y más letal.",
                    "Identificar la carga roja y eliminarlo a máxima distancia. El tiempo adicional de detonación es la única ventana fiable de escape.",
                    "Republic of Nusia", "Assault rifle + body-mounted dynamite", "Advanced kamikaze", "HOSTILE",
                    "Master of ultimate suicide tactics and a silent enemy. It carries an assault rifle and an extreme quantity of dynamite attached to its body. Detonation takes longer than a common Kamikaze unit, but the resulting explosion is considerably larger and deadlier.",
                    "Identify the red payload and eliminate it at maximum range. The longer detonation time is the only reliable escape window."),
            file("ADV-003", "ARTILLER", "ADVANCED", 5, "500", "artiller",
                    "República de Nusia", "SMG + Radio Striker", "Flame Strike / misiles / nuclear", "HOSTIL",
                    "Especialista en bombardeo encubierto. En lugar de correr hacia el jugador, selecciona un punto seguro, permanece oculto y solicita ataques con su Radio Striker. Puede ordenar Flame Strikes, misiles pequeños, medianos o grandes y, en el extremo superior, bombas nucleares.",
                    "Localizar la transmisión y obligarlo a abandonar su posición antes de que complete la solicitud. No permanecer dentro de la zona marcada.",
                    "Republic of Nusia", "SMG + Striker Radio", "Flame Strike / missiles / nuclear", "HOSTILE",
                    "A covert bombardment specialist. Instead of rushing the player, it selects a protected location, remains hidden and calls attacks through a Striker Radio. Available strikes include Flame Strikes, small, medium and large missiles and, at the highest level, nuclear bombs.",
                    "Locate the transmission and force it from its position before the request completes. Never remain inside the marked zone."),
            file("ADV-004", "CLOAKER", "ADVANCED", 5, "150", "cloaker",
                    "República de Nusia", "Exoesqueleto + visión nocturna", "Cazador de alta velocidad", "HOSTIL",
                    "Maestro de caza absoluta. Aunque no porta un arma convencional, su exoesqueleto permite velocidades extremas y saltos muy altos. Emite pulsos de radar antes de correr hacia el objetivo con un chillido. Al alcanzarlo ejecuta un dropkick de 100.000 de daño que ignora completamente la armadura y mata en cualquier dificultad. Sus gafas nocturnas permiten cazar en oscuridad total.",
                    "El chillido confirma la carga. Separarse y cortar inmediatamente su trayectoria; no existe armadura capaz de resistir el impacto.",
                    "Republic of Nusia", "Exoskeleton + night vision", "High-speed hunter", "HOSTILE",
                    "Master of absolute hunting. Although it carries no conventional weapon, its exoskeleton enables extreme speed and very high jumps. It emits radar pulses before sprinting at the target with a screech. On contact it performs a 100,000-damage dropkick that completely ignores armour and kills on every difficulty. Night-vision goggles allow it to hunt in total darkness.",
                    "The screech confirms the charge. Split up and break its path immediately; no armour can survive the impact."),
            file("ADV-005", "APU", "ADVANCED", 5, "120,000", "apu",
                    "República de Nusia", "Mech de californita + lanzallamas", "Defensa reducida en agua", "HOSTIL",
                    "Maestro de la robótica hostil. Un piloto con casco de protección controla un exoesqueleto de californita armado con lanzallamas. Cuenta con 120.000 HP y 0,75 de defensa, ajustables por dificultad. Al acercarse quema continuamente, ignora los I-frames y vuelve inútiles los tótems. Su defensa cae dentro del agua.",
                    "Mantener distancia, atraerlo al agua y evitar por completo su arco frontal. No confiar en tótems ni en invulnerabilidad temporal.",
                    "Republic of Nusia", "Californite mech + flamethrower", "Reduced defence in water", "HOSTILE",
                    "Master of hostile robotics. A helmeted pilot controls a Californite exoskeleton armed with a flamethrower. It has 120,000 HP and 0.75 defence, adjusted by difficulty. At close range it burns continuously, ignores I-frames and renders totems useless. Its defence falls in water.",
                    "Keep it at range, lure it into water and avoid its frontal fire arc completely. Do not rely on totems or temporary invulnerability."),
            file("ADV-006", "MISSILER", "ADVANCED", 4, "250", "missiler",
                    "República de Nusia", "PVS-14 + Javelin + 8 DEF", "Francotirador de misiles guiados", "HOSTIL",
                    "Maestro de los teledirigidos y evolución avanzada del Sniper. Se desplaza en invisibilidad, elige una posición lejana y lanza misiles guiados. No proyecta un láser: aparece un destello amarillo que concede cinco segundos para escapar. Si detecta jugadores acercándose, desaparece nuevamente y selecciona otra posición.",
                    "Abandonar el área inmediatamente al ver el destello amarillo. Acercarse en grupo obliga al Missiler a interrumpir el ataque y reposicionarse.",
                    "Republic of Nusia", "PVS-14 + Javelin + 8 DEF", "Guided-missile sniper", "HOSTILE",
                    "Master of guided weaponry and an advanced evolution of the Sniper. It moves while invisible, selects a distant position and launches guided missiles. No laser is projected: a yellow flash grants five seconds to escape. If players approach, it vanishes again and selects another position.",
                    "Leave the area immediately when the yellow flash appears. A coordinated approach forces the Missiler to interrupt its attack and relocate."),
            tankFile("TNK-001", "ZAPPER", 4, "3,000", "100", "zapper",
                    "República de Nusia", "Bastón eléctrico + bobinas Tesla", "Melee / distancia / antitécnicas", "HOSTIL",
                    "Unidad tanque nusiana y minijefe poco frecuente. Su bastón controla corrientes, ondas y láseres letales, mientras las bobinas Tesla de la espalda recargan el sistema. Puede combatir sin apoyo y adaptarse a distintos entornos. Un impacto directo contra un objetivo sin armadura puede electrocutarlo y aturdirlo durante varios minutos; los disparos adicionales prolongan el efecto.",
                    "Usar aislamiento y cobertura sólida. Interrumpir la recarga de las bobinas, evitar encadenar impactos eléctricos y no enfrentarlo sin armadura.",
                    "Republic of Nusia", "Electric staff + Tesla coils", "Melee / ranged / anti-technique", "HOSTILE",
                    "A rare Nusian tank unit and field mini-boss. Its staff controls lethal currents, waves and lasers while the Tesla coils on its back recharge the system. It needs no common-unit support and can adapt to different environments. A direct hit on an unarmoured target can electrocute and stun for several minutes; additional shots extend the effect.",
                    "Use insulation and solid cover. Interrupt the coil recharge, avoid chained electric hits and never engage it without armour."),
            tankFile("TNK-002", "COMBATANT", 4, "3,000", "100", "combatant",
                    "República de Nusia", "M48 Tomahawk + armadura pesada", "Carga con control de trayectoria", "HOSTIL",
                    "Tanque de asalto pesado y deliberadamente ruidoso. Trota hasta localizar jugadores y se lanza al combate con una M48 Tomahawk capaz de proyectar ataques en varias direcciones. Su carga causa hasta 650 HP de daño y tiene un 75% de probabilidad de ignorar defensas, aunque puede esquivarse si el Combatant todavía no ha aprendido a corregir la trayectoria.",
                    "Mantener distancia y concentrar fuego a distancia. No pelear cuerpo a cuerpo; guardar movilidad para esquivar la carga y atacar durante su recuperación.",
                    "Republic of Nusia", "M48 Tomahawk + heavy armour", "Trajectory-controlled charge", "HOSTILE",
                    "A loud heavy-assault tank. It trots until players are found, then commits to close combat with an M48 Tomahawk capable of projecting attacks in several directions. Its charge deals up to 650 HP and has a 75% chance to ignore defences, although it can be dodged while the Combatant has not learned to correct its trajectory.",
                    "Keep your distance and focus ranged fire. Avoid close combat, preserve mobility for the charge and attack during its recovery."),
            tankFile("TNK-003", "AGREEMENT", 0, "3,000", "100", "agreement",
                    "Corporación Secure Contain Protect", "Portales y visores: reporte sin verificar", "Gates / Rifts (testimonio)", "REPORTE SIN VERIFICAR",
                    AgreementReport.ES, AgreementReport.ADVICE_ES,
                    "Secure Contain Protect Corporation", "Portals and visors: unverified report", "Gates / Rifts (testimony)", "UNVERIFIED REPORT",
                    AgreementReport.EN, AgreementReport.ADVICE_EN),
            tankFile("TNK-004", "JAGANT", 0, "2,500", "100", "jagant",
                    "Sin registro confirmado", "Información no recuperada", "Sin registro", "ARCHIVO INCOMPLETO",
                    "El archivo únicamente conserva el nombre Jagant, una captura parcial y sus valores estimados de resistencia. Su origen, armamento, capacidades y patrón de despliegue siguen sin confirmar.",
                    "Evitar conclusiones basadas solo en la imagen. Registrar cada encuentro y mantener distancia hasta identificar su método de ataque.",
                    "No confirmed record", "Information not recovered", "No record", "INCOMPLETE FILE",
                    "The file only preserves the Jagant name, a partial capture and estimated durability values. Its origin, weapons, capabilities and deployment pattern remain unconfirmed.",
                    "Avoid conclusions based on the image alone. Record every encounter and keep your distance until its attack method is identified."),
            tankFile("TNK-005", "STRIDER", 0, "2,500", "100", "strider",
                    "Sin registro confirmado", "Información no recuperada", "Render recuperado", "ARCHIVO INCOMPLETO",
                    "Se recuperó un render de una estructura mecánica de patas largas identificada como Strider. No existe información verificada sobre su armamento, movilidad, autonomía, origen o comportamiento en combate.",
                    "No aproximarse basándose únicamente en su apariencia. Priorizar observación remota y registrar cualquier patrón de movimiento o emisión de energía.",
                    "No confirmed record", "Information not recovered", "Recovered render", "INCOMPLETE FILE",
                    "A render of a long-legged mechanical structure identified as Strider was recovered. There is no verified information about weapons, mobility, autonomy, origin or combat behaviour.",
                    "Do not approach based on appearance alone. Prioritise remote observation and record any movement pattern or energy emission."),
            file("ELT-001", "AGARES", "ELITE", 2, "25,000", "agares",
                    "Sin registro confirmado", "Telequinesis + magnetizadores + sabotaje total", "Agente científico Two Sides", "ÉLITE HOSTIL",
                    "Jefe Élite con una maestría absoluta sobre la telequinesis y capacidad para sabotear todos los dispositivos existentes, sin importar su calidad. Usa sus poderes para alejar y lanzar a los jugadores que se aproximan. Contra un cyborg puede emplear magnetizadores para causar daño extremo, fallos fatales e incluso una muerte instantánea. También fabrica teletransportadores que permanecen indestructibles mientras Agares siga con vida. Aparece con un traje científico mitad rojo y mitad azul Two Sides, pantalones grises y gafas de realidad aumentada capaces de escanear jugadores en oscuridad absoluta.",
                    "Reconocimiento Aéreo, Stronghold 5-5: se verificó una unidad Élite Agares. Actuar de inmediato si se aproxima a un dispositivo eléctrico, mantener alejados a los cyborgs y eliminar a Agares antes de intentar destruir sus teletransportadores.",
                    "No confirmed record", "Telekinesis + magnetisers + total sabotage", "Two Sides scientific agent", "HOSTILE ELITE",
                    "An Elite boss with absolute mastery of telekinesis and the ability to sabotage every known device regardless of quality. It uses its powers to repel and throw approaching players. Against a cyborg, it can use magnetisers to cause extreme damage, fatal malfunctions and even an instant kill. It also manufactures teleporters that remain indestructible for as long as Agares is alive. It appears in a half-red, half-blue Two Sides scientific suit, grey trousers and augmented-reality glasses capable of scanning players in complete darkness.",
                    "Aerial Recon, Stronghold 5-5: an Elite Agares unit has been verified. Act immediately if it approaches an electrical device, keep cyborgs away and eliminate Agares before attempting to destroy its teleporters."),
            file("ELT-002", "GHOST", "ELITE", 1, "25,000", "ghost",
                    "Sin registro confirmado", "Daga venenosa forjada + dinamita Creeper", "Infiltrante de invisibilidad permanente", "ÉLITE HOSTIL",
                    "Jefe Élite infiltrante equipado con una daga venenosa forjada y capacidad de invisibilidad sin tiempo de recarga. Intenta sorprender y apuñalar a los jugadores por la espalda; si falla y es descubierto, ataca directamente en lugar de huir. Puede usar dinamitas Creeper para atraer la atención y atacar desde otro lado. Ghost aparece como un agente con traje verde, rostro sombreado y capucha.",
                    "Reconocimiento Aéreo, Stronghold 5-5: se detectó una unidad Élite Ghost. Mantenerse alerta, permanecer en grupos, cubrir la retaguardia y no abandonar la formación para perseguir una explosión señuelo.",
                    "No confirmed record", "Forged poison dagger + Creeper dynamite", "Permanent-invisibility infiltrator", "HOSTILE ELITE",
                    "An infiltrator Elite boss equipped with a forged poison dagger and invisibility with no cooldown. It attempts to surprise and stab players from behind; if the attack fails and it is spotted, it assaults them directly instead of fleeing. It can use Creeper dynamite to draw attention before attacking from another direction. Ghost appears as an agent in a green suit with a shadowed face and hood.",
                    "Aerial Recon, Stronghold 5-5: an Elite Ghost unit has been detected. Stay alert, remain in groups, cover your rear and do not break formation to pursue a decoy explosion."),
            file("ELT-003", "AURELIONIS", "ELITE", 0, "1", "aurelionis",
                    "???", "???", "???", "???", "???", "???",
                    "???", "???", "???", "???", "???", "???"),
            file("SUP-001", "ATLAS", "SUPER-UNIT", 5, "125,000,000", "atlas",
                    "Sin registro confirmado", "Información no recuperada", "Super Unit", "ALERTA MÁXIMA",
                    "Atlas está clasificado como Super Unit y posee una resistencia confirmada de 125.000.000 HP. No se recuperaron datos verificados sobre su origen, armamento, capacidades especiales o patrón de despliegue.",
                    "No inferir capacidades a partir del metraje. Mantener observación remota, evitar el contacto sin preparación y registrar cualquier comportamiento antes de definir un protocolo de combate.",
                    "No confirmed record", "Information not recovered", "Super Unit", "MAXIMUM ALERT",
                    "Atlas is classified as a Super Unit with a confirmed durability of 125,000,000 HP. No verified data has been recovered about its origin, weapons, special capabilities or deployment pattern.",
                    "Do not infer capabilities from the footage. Maintain remote observation, avoid unprepared contact and record all behaviour before defining a combat protocol."),
            bossFile("BOS-001", "TEMPEST", 5, "8,000", "tempest",
                    "Sin registro confirmado", "Pistola de rayos + descarga eléctrica + bobinas Tesla", "Eléctrico / semiacuático / sabotaje", "JEFE HOSTIL",
                    "Jefe especializado en controlar multitudes mediante armamento eléctrico y semiacuático. Su pistola de rayos daña a grupos completos y la descarga de corto alcance puede freír instantáneamente a las víctimas cercanas. Dos bobinas Tesla alimentan el sistema. El daño aumenta cuanto menor sea la distancia y Tempest también puede sabotear habilidades.",
                    "Reconocimiento Aéreo, Stronghold 5-5: Tempest se dirige hacia la zona. No amontonarse, mantener una separación amplia y evitar por completo su descarga de corto alcance.",
                    "No confirmed record", "Ray pistol + electric discharge + Tesla coils", "Electric / semi-aquatic / sabotage", "HOSTILE BOSS",
                    "A crowd-control boss equipped with electric and semi-aquatic weaponry. Its ray pistol damages entire groups and its short-range discharge can instantly fry nearby victims. Two Tesla coils power the system. Damage rises as distance closes, and Tempest can also sabotage abilities.",
                    "Aerial Recon, Stronghold 5-5: Tempest is moving towards the area. Do not cluster, keep wide spacing and avoid its short-range discharge completely."),
            bossFile("BOS-002", "FUSILIER", 5, "8,000", "fusilier",
                    "Sin registro confirmado", "Lanzagranadas de seis disparos + pala", "Bombardeo de largo alcance", "JEFE HOSTIL // LENTO",
                    "Jefe blindado de largo alcance que bombardea posiciones con un lanzagranadas de seis disparos. Si un jugador consigue acercarse, utiliza una pala como defensa. El registro visual confirma gorro, gafas protectoras, armadura pesada y movilidad reducida.",
                    "Reconocimiento Aéreo, sector 5-5: se detectó un Fusilier. Abandonar inmediatamente el área marcada por el proyectil y aprovechar su lentitud para cambiar de cobertura.",
                    "No confirmed record", "Six-shot grenade launcher + shovel", "Long-range bombardment", "HOSTILE BOSS // SLOW",
                    "A long-range armoured boss that bombards positions with a six-shot grenade launcher. If a player closes the distance, it uses a shovel for defence. Visual records confirm a cap, protective goggles, heavy armour and reduced mobility.",
                    "Aerial Recon, sector 5-5: a Fusilier has been detected. Leave the projectile impact area immediately and exploit its slow movement to change cover."),
            bossFile("BOS-003", "ACHILLES", 5, "15,000", "achilles",
                    "Sin registro confirmado", "Francotirador Armour Peeler de alta frecuencia", "Perforación total de armadura", "JEFE HOSTIL // AGONÍA // LENTO",
                    "Jefe francotirador equipado con un Armour Peeler de alta frecuencia. El proyectil ignora por completo la armadura y causa todavía más daño a objetivos protegidos. Su puntería es promedio y se desplaza lentamente; el registro muestra armadura ligera, auriculares y una radio de comunicaciones.",
                    "Reconocimiento Aéreo, Stronghold 5-5: una unidad Achilles apoya a las fuerzas enemigas. Romper las líneas de visión y atacar únicamente durante las ventanas en que sus defensas estén desactivadas.",
                    "No confirmed record", "High-frequency Armour Peeler sniper", "Complete armour penetration", "HOSTILE BOSS // AGONY // SLOW",
                    "A sniper boss equipped with a high-frequency Armour Peeler. Its projectile completely ignores armour and deals even more damage to protected targets. Its aim is average and movement is slow; records show light armour, headphones and a communications radio.",
                    "Aerial Recon, Stronghold 5-5: an Achilles unit is supporting enemy forces. Break dangerous sight lines and attack only during windows when its defences are disabled."),
            bossFile("BOS-004", "TRIDENT", 5, "38,000", "trident",
                    "Sin registro confirmado", "Machete de alta frecuencia + gancho de resistencia máxima", "Gancho / ejecución / carga", "JEFE HOSTIL",
                    "Agente fuertemente blindado que atrae jugadores con un gancho y desenvaina un machete de alta frecuencia al tenerlos cerca. El golpe próximo es una ejecución instantánea y puede rematar objetivos caídos. Si la víctima se aleja demasiado, Trident carga a gran velocidad. Porta visera opaca, pantalones hazmat mostaza, hombreras y guantes negros.",
                    "Reconocimiento Aéreo, Stronghold 5-5: tenemos un Trident. Mantener distancia, permanecer coordinados y cortar la trayectoria del gancho; acercarse permite su ejecución inmediata.",
                    "No confirmed record", "High-frequency machete + maximum-strength hook", "Hook / execution / charge", "HOSTILE BOSS",
                    "A heavily armoured agent that pulls players in with a hook and draws a high-frequency machete at close range. The nearby strike is an instant execution and can finish downed targets. If a victim moves too far away, Trident charges at high speed. It wears an opaque visor, mustard hazmat trousers, shoulder pads and black gloves.",
                    "Aerial Recon, Stronghold 5-5: a Trident is present. Keep distance, remain coordinated and break the hook trajectory; moving close enables its immediate execution."),
            bossFile("BOS-005", "PROMETHEUS", 5, "8,000", "prometheus",
                    "Sin registro confirmado", "FAHRENNEIT-3000 + dos tanques de combustible", "Incineración / dispositivo de alejamiento", "JEFE HOSTIL",
                    "Jefe incendiario equipado con un lanzallamas FAHRENNEIT-3000 y dos tanques de combustible. Su arma prende fuego a los jugadores y un dispositivo defensivo castiga a quienes se acercan demasiado, expulsándolos con gran fuerza y daño. El agente usa máscara de gas, frac, chaleco, hombreras y muñequeras tácticas.",
                    "Reconocimiento Aéreo, Stronghold 5-5: Prometheus fue desplegado. Mantenerse fuera del arco del lanzallamas y concentrar los ataques sobre sus tanques de combustible.",
                    "No confirmed record", "FAHRENNEIT-3000 + two fuel tanks", "Incineration / repulsion device", "HOSTILE BOSS",
                    "An incendiary boss equipped with a FAHRENNEIT-3000 flamethrower and two fuel tanks. Its weapon sets players ablaze, while a defensive device punishes anyone who moves too close by throwing them away with severe damage. The agent wears a gas mask, tailcoat, tactical vest, shoulder pads and wrist guards.",
                    "Aerial Recon, Stronghold 5-5: Prometheus has been deployed. Stay outside the flamethrower arc and concentrate attacks on its fuel tanks."),
            bossFile("BOS-006", "DAEDALUS", 5, "N/D", "daedalus",
                    "Sin registro confirmado", "Pico de combate de acero de improbabilidad", "Minería supersónica / emboscada subterránea", "JEFE HOSTIL",
                    "Jefe minero capaz de excavar bajo tierra a velocidad supersónica para emerger delante o detrás de su objetivo. Su pico parece común, pero está forjado con lingotes de acero de improbabilidad de frecuencia media. Puede dejar fuera de combate a un rival en tres a cinco golpes, o en uno solo si no lleva armadura pesada o moderna. También porta casco minero con rayos X, armadura naranja y vendas de curación pasiva.",
                    "Reconocimiento Aéreo, Stronghold 5-5: un Daedalus está en movimiento. Vigilar la retaguardia, no deambular solo y cambiar de posición cuando desaparezca bajo tierra.",
                    "No confirmed record", "Improbability-steel combat pickaxe", "Supersonic mining / underground ambush", "HOSTILE BOSS",
                    "A mining boss capable of tunnelling underground at supersonic speed before emerging ahead of or behind its target. Its pickaxe appears ordinary but is forged from medium-frequency improbability steel. It can incapacitate an opponent in three to five hits, or one hit without heavy or modern armour. It also carries an X-ray mining helmet, orange tactical armour and passive self-healing bandages.",
                    "Aerial Recon, Stronghold 5-5: a Daedalus is moving. Watch your rear, never wander alone and relocate whenever it disappears underground."),
            bossFile("BOS-007", "HERMES", 0, "45,000", "hermes",
                    "Sin registro confirmado", "Información no recuperada", "Video de archivo recuperado", "EXPEDIENTE INCOMPLETO",
                    "Existe metraje de archivo asociado a la designación Hermes y una resistencia estimada de 45.000 HP. No hay datos verificados sobre origen, armamento, capacidades, comportamiento o condiciones de despliegue.",
                    "No deducir habilidades únicamente a partir del video. Mantener observación remota, registrar cada movimiento y tratar a Hermes como un jefe hostil hasta completar el expediente.",
                    "No confirmed record", "Information not recovered", "Recovered archival video", "INCOMPLETE FILE",
                    "Archival footage linked to the Hermes designation exists, along with an estimated durability of 45,000 HP. There is no verified information about origin, weapons, capabilities, behaviour or deployment conditions.",
                    "Do not infer abilities from the video alone. Maintain remote observation, record every movement and treat Hermes as a hostile boss until the dossier is complete."),
            bossFile("BOS-008", "LELANTOS", 0, "8,000", "lelantos",
                    "Sin registro confirmado", "Información no recuperada", "Video de archivo recuperado", "EXPEDIENTE INCOMPLETO",
                    "Solo se recuperaron la designación Lelantos, un video de reconocimiento y una resistencia estimada de 8.000 HP. Su armamento, habilidades, origen y patrón táctico permanecen sin confirmar.",
                    "No completar la información con suposiciones. Analizar el metraje, evitar el contacto cercano y documentar cualquier capacidad observada en combate.",
                    "No confirmed record", "Information not recovered", "Recovered archival video", "INCOMPLETE FILE",
                    "Only the Lelantos designation, reconnaissance footage and an estimated durability of 8,000 HP were recovered. Its weapons, abilities, origin and tactical pattern remain unconfirmed.",
                    "Do not fill missing information with assumptions. Analyse the footage, avoid close contact and document any capability observed in combat."),
            bossFile("BOS-009", "GAIA", 0, "20,000", "gaia",
                    "Sin registro confirmado", "Información no recuperada", "Video de archivo recuperado", "EXPEDIENTE INCOMPLETO",
                    "El archivo de Gaia contiene metraje parcial y una resistencia estimada de 20.000 HP. No existen registros verificados sobre armamento, capacidades, afiliación o comportamiento de combate.",
                    "La presencia de otras figuras en el metraje no confirma aliados ni duplicados. Mantener distancia y registrar el primer encuentro operativo antes de clasificar a Gaia.",
                    "No confirmed record", "Information not recovered", "Recovered archival video", "INCOMPLETE FILE",
                    "The Gaia file contains partial footage and an estimated durability of 20,000 HP. There are no verified records about weapons, capabilities, affiliation or combat behaviour.",
                    "Other figures visible in the footage do not confirm allies or duplicates. Keep your distance and record the first operational encounter before classifying Gaia."));

    private static IntelEntry file(String code, String name, String category, int threat, String hp, String image,
                                   String esOrigin, String esArmament, String esVariants, String esStatus, String esDescription, String esAdvisory,
                                   String enOrigin, String enArmament, String enVariants, String enStatus, String enDescription, String enAdvisory) {
        return new IntelEntry(code, name, category, threat, hp, "N/D", image,
                new IntelEntry.IntelText(esOrigin, esArmament, esVariants, esStatus, esDescription, esAdvisory),
                new IntelEntry.IntelText(enOrigin, enArmament, enVariants, enStatus, enDescription, enAdvisory));
    }

    private static IntelEntry tankFile(String code, String name, int threat, String hp, String defense, String image,
                                       String esOrigin, String esArmament, String esVariants, String esStatus, String esDescription, String esAdvisory,
                                       String enOrigin, String enArmament, String enVariants, String enStatus, String enDescription, String enAdvisory) {
        return new IntelEntry(code, name, "TANK", threat, hp, defense, image,
                new IntelEntry.IntelText(esOrigin, esArmament, esVariants, esStatus, esDescription, esAdvisory),
                new IntelEntry.IntelText(enOrigin, enArmament, enVariants, enStatus, enDescription, enAdvisory));
    }

    private static IntelEntry bossFile(String code, String name, int threat, String hp, String image,
                                       String esOrigin, String esArmament, String esVariants, String esStatus, String esDescription, String esAdvisory,
                                       String enOrigin, String enArmament, String enVariants, String enStatus, String enDescription, String enAdvisory) {
        return new IntelEntry(code, name, "BOSS", threat, hp, "N/D", "bosses/" + image + "/frame_00",
                new IntelEntry.IntelText(esOrigin, esArmament, esVariants, esStatus, esDescription, esAdvisory),
                new IntelEntry.IntelText(enOrigin, enArmament, enVariants, enStatus, enDescription, enAdvisory));
    }

}

