package uy.santipdr.siege.client;

import java.util.List;

/**
 * Current player-facing SIEGE 5.00 knowledge.
 *
 * Older records stay available to maintainers in the previous data files, but this
 * layer intentionally replaces stale recipes, technical audit wording and vague
 * one-line summaries with the latest useful explanation for a player.
 */
public final class SiegeKnowledgeExpansion50 {
    private SiegeKnowledgeExpansion50() { }

    private static SiegeKnowledgeData.Source src(SiegeKnowledgeData.Confidence confidence,
                                                  String date, String section,
                                                  String es, String en) {
        return new SiegeKnowledgeData.Source(confidence, date, section, es, en);
    }

    private static SiegeKnowledgeData.Entry e(String id, SiegeKnowledgeData.Domain domain,
                                               String titleEs, String titleEn,
                                               String summaryEs, String summaryEn,
                                               String bodyEs, String bodyEn,
                                               boolean critical, List<String> related,
                                               SiegeKnowledgeData.Source... sources) {
        return new SiegeKnowledgeData.Entry(id, SiegeKnowledgeData.Zone.SERVER, domain,
                titleEs, titleEn, summaryEs, summaryEn, bodyEs, bodyEn,
                critical, related, List.of(sources));
    }

    private static final List<SiegeKnowledgeData.Entry> ENTRIES = List.of(
            e("server-overview", SiegeKnowledgeData.Domain.OVERVIEW,
                    "Eternal Craft — SIEGE", "Eternal Craft — SIEGE",
                    "Supervivencia que empieza como Minecraft normal y termina mezclándose con razas, habilidades, amenazas, guerras y sistemas propios.",
                    "Survival that starts like normal Minecraft and gradually mixes in races, abilities, threats, wars and its own systems.",
                    "No hace falta aprender todo antes de entrar. Podés empezar consiguiendo comida, herramientas, armadura y un lugar seguro como en cualquier supervivencia. La diferencia aparece a medida que avanzás: tu raza puede abrir habilidades y progresiones propias, hay enemigos que no se comportan como mobs normales y existen sistemas que conviene conocer antes de arriesgar objetos difíciles de recuperar.\n\nSIEGE transcurre en una guerra de 2044. Nusia, Desperado, World Marshal, SCP y otras amenazas forman parte del conflicto; Dominion of Pinzhao y Stronghold 5-5 aparecen como parte central del frente. La idea de esta guía es explicar qué necesitás para jugar, no describir cómo se recopiló la información.",
                    "You do not need to learn everything before joining. You can begin by getting food, tools, armor and a safe place just like any survival world. The difference appears as you progress: your race can unlock its own abilities and progression, some enemies do not behave like normal mobs, and several systems are worth understanding before risking hard-to-replace items.\n\nSIEGE takes place during a war in 2044. Nusia, Desperado, World Marshal, SCP and other threats are part of the conflict; Dominion of Pinzhao and Stronghold 5-5 are central parts of the front. This guide explains what you need to play rather than how the information was collected.",
                    true, List.of("newcomer-operational-rule"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Inicio",
                            "Resumen actual del servidor.", "Current server overview.")),

            e("newcomer-operational-rule", SiegeKnowledgeData.Domain.OVERVIEW,
                    "Cómo empezar", "How to start",
                    "Primero sobreviví y armá una base; después aprendé tu raza y los sistemas que realmente te afectan.",
                    "Survive and establish a base first; then learn your race and the systems that actually affect you.",
                    "1. Empezá por lo básico: comida, herramientas, armadura, refugio y recursos. No necesitás una raza perfecta ni un objeto raro para comenzar.\n\n2. No te separes sin avisar. La coordinación importa mucho porque hay amenazas capaces de dejarte fuera de combate muy rápido.\n\n3. Prestá atención a lo nuevo. Si aparece una estructura, objeto, enemigo o efecto que no conocés, anotá qué pasó antes de probarlo otra vez. Buena parte del progreso sale de entender el entorno.\n\n4. Revisá tu raza. Aprendé qué hace en su estado inicial, si usa V1→V4 o una progresión distinta y qué habilidades puede abrir.\n\n5. Recién después metete con Trials, reliquias, Assembling y otros sistemas costosos. Si todavía no sabés qué hace algo raro, guardarlo suele ser mejor que gastarlo a ciegas.\n\nTres hábitos resumen bien el comienzo: instinto de supervivencia, coordinación y registrar lo que descubrís.",
                    "1. Start with the basics: food, tools, armor, shelter and resources. You do not need a perfect race or a rare item to begin.\n\n2. Do not split from the group without warning. Coordination matters because some threats can take you out very quickly.\n\n3. Pay attention to new things. If you find an unknown structure, item, enemy or effect, note what happened before trying it again. A lot of progression comes from understanding the environment.\n\n4. Check your race. Learn what it does at its initial state, whether it uses V1→V4 or a different progression, and which abilities it can unlock.\n\n5. Only then move into Trials, relics, Assembling and other expensive systems. If you still do not know what a rare item does, saving it is usually better than spending it blindly.\n\nThree habits summarize the beginning well: survival instinct, coordination and keeping track of what you discover.",
                    true, List.of("race-system", "abilities-experience", "executors-basics", "death-revive-current"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "20/09/2026", "Consejos para nuevos",
                            "Instinto de supervivencia, coordinación y anotación fueron señalados como la base para empezar.",
                            "Survival instinct, coordination and note-taking were identified as the core starting habits.")),

            e("server-exploration", SiegeKnowledgeData.Domain.OVERVIEW,
                    "Explorar sin regalar la vida", "Exploring without throwing your life away",
                    "Explorar sirve, pero primero conviene saber cómo volver y qué hacer si aparece algo que no podés enfrentar.",
                    "Exploration matters, but first know how to return and what to do when you meet something you cannot fight.",
                    "Llevá comida, una forma de orientarte y equipo que estés dispuesto a perder. Si vas en grupo, acordá quién guía y dónde se reúnen si se separan. No todo lo que aparece está pensado para pelearse en el momento: reconocer una amenaza y retirarse también es progreso.\n\nSi encontrás algo desconocido, guardá su nombre o ubicación y consultalo en el Atlas antes de gastar recursos. El objetivo de explorar no es entrar a todo; es volver con más información y mejores opciones.",
                    "Carry food, a way to orient yourself and gear you can afford to lose. If you are in a group, agree on who leads and where to regroup if separated. Not everything you meet is meant to be fought immediately: recognizing a threat and retreating is also progress.\n\nIf you find something unknown, save its name or location and check the Atlas before spending resources. Exploration is not about entering everything; it is about coming back with more information and better options.",
                    false, List.of("newcomer-operational-rule", "executors-basics"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Exploración",
                            "Consejo general derivado de incidentes repetidos de exploración y coordinación.",
                            "General advice derived from repeated exploration and coordination incidents.")),

            e("race-system", SiegeKnowledgeData.Domain.RACES,
                    "Cómo funcionan las razas", "How races work",
                    "La raza define una parte importante de tus capacidades y puede tener progresiones, transformaciones o condiciones propias.",
                    "Your race defines an important part of your capabilities and may have its own progression, transformations or conditions.",
                    "Las razas no son sólo un nombre o una rareza. Pueden cambiar atributos, dar acceso a habilidades y abrir formas de progresión que otras razas no tienen. Algunas siguen una ruta V1→V4; otras avanzan mediante entrenamiento, transformaciones, Trials, objetos o pasos especiales.\n\nLos giros de raza cambian la raza actual por otra al azar. Un giro no garantiza una rareza mejor y pueden repetirse resultados. También existen razas que no se obtienen mediante un giro común y requieren otros pasos.\n\nAntes de intentar mejorar una raza, abrí su ficha individual. Ahí debe aparecer la ruta conocida de esa raza y, cuando falte información, se marca como desconocida en lugar de inventar un requisito.",
                    "Races are more than a name or rarity. They can change attributes, grant access to abilities and unlock progression paths other races do not have. Some follow V1→V4; others progress through training, transformations, Trials, items or special steps.\n\nRace rerolls replace the current race with another random result. A reroll does not guarantee a better rarity and results can repeat. Some races are not obtained through a normal reroll and require other steps.\n\nBefore trying to improve a race, open its individual entry. Its known progression path should be shown there, and missing information is marked as unknown instead of inventing a requirement.",
                    true, List.of("race-catalog", "rarity-order", "progression-v1-v4"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Razas",
                            "Los giros, pasos especiales y progresiones distintas aparecen repetidamente en el registro.",
                            "Rerolls, special steps and distinct progression paths recur throughout the records.")),

            e("race-catalog", SiegeKnowledgeData.Domain.RACES,
                    "Razas", "Races",
                    "Cada raza tiene su propia ficha; la lista sirve para encontrarla sin juntar toda la información en un solo bloque.",
                    "Each race has its own entry; the list is meant to find it without packing everything into one block.",
                    "Usá el Atlas de Razas para buscar una raza por nombre. La ficha muestra su rareza conocida, el tipo de progresión y la información que existe sobre sus habilidades o evoluciones.\n\nNo todas las razas están entendidas al mismo nivel. Si un paso de V2, V3, V4, una transformación o una variante todavía no está claro, la ficha debe decirlo directamente. No se rellena el hueco con una regla genérica de otra raza.",
                    "Use the Race Atlas to search by name. Each entry shows its known rarity, progression type and the information available about its abilities or evolutions.\n\nNot every race is understood equally well. If a V2, V3, V4 step, transformation or variant is still unclear, the entry should say so directly. Missing information is not filled with a generic rule from another race.",
                    false, List.of("race-system", "rarity-order"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Razas",
                            "Catálogo actual de razas conocidas.", "Current known-race catalog.")),

            e("rarity-order", SiegeKnowledgeData.Domain.RACES,
                    "Rarezas de raza", "Race rarities",
                    "Orden actual de menor a mayor rareza.", "Current order from lower to higher rarity.",
                    "Común → Poco común → Raro → Ultra raro → Legendario → Obsainan → Mítico → Godly → Eternal → Fabled.\n\nLa rareza no explica por sí sola cómo se progresa una raza ni reemplaza su ficha. Sirve para ubicar qué tan poco común es el resultado dentro del sistema de razas.",
                    "Common → Uncommon → Rare → Ultra Rare → Legendary → Obsainan → Mythic → Godly → Eternal → Fabled.\n\nRarity alone does not explain how a race progresses and does not replace its individual entry. It describes how uncommon that result is within the race system.",
                    true, List.of("race-system", "race-catalog"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "20/09/2026", "Rarezas",
                            "Orden de rarezas confirmado en el registro más reciente.",
                            "Rarity order confirmed in the most recent records.")),

            e("abilities-experience", SiegeKnowledgeData.Domain.ABILITIES,
                    "Habilidades, niveles y experiencia", "Abilities, levels and experience",
                    "Las habilidades no aparecen todas de golpe: algunas dependen de tu raza, progresión, entrenamiento o nivel en otro sistema.",
                    "Abilities do not all appear at once: some depend on your race, progression, training or level in another system.",
                    "Tu raza puede darte habilidades propias y versiones superiores pueden abrir más usos o capacidades. Además existen habilidades ligadas a otros sistemas, por ejemplo meditación o elementos.\n\nNo conviene asumir que tener más nivel desbloquea cualquier cosa. Cada ruta puede tener sus propios requisitos, cooldowns o recursos. Si una habilidad pertenece a una raza concreta, la información debe estar dentro de esa raza; si pertenece a un sistema general, debe aparecer en el Atlas.",
                    "Your race may grant its own abilities and higher stages can unlock additional uses or capabilities. Other abilities are tied to separate systems such as meditation or elements.\n\nDo not assume that more levels unlock everything. Each path can have its own requirements, cooldowns or resources. If an ability belongs to a specific race, the information belongs in that race entry; if it belongs to a general system, it belongs in the Atlas.",
                    false, List.of("race-system", "progression-v1-v4", "trials-basics"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Habilidades",
                            "El registro muestra habilidades raciales y sistemas con progresión propia.",
                            "The records show both racial abilities and systems with their own progression.")),

            e("progression-v1-v4", SiegeKnowledgeData.Domain.PROGRESSION,
                    "Progresión racial V1 → V4", "Race progression V1 → V4",
                    "V1, V2, V3 y V4 son etapas de evolución para las razas que usan este sistema; no son cuatro razas distintas.",
                    "V1, V2, V3 and V4 are evolution stages for races that use this system; they are not four separate races.",
                    "V1 es la etapa inicial. En muchas razas sus efectos todavía son discretos. V2 suele hacer más visibles los atributos o habilidades y puede abrir usos que V1 no tenía. V3 y V4 continúan la progresión, pero sus requisitos dependen de la raza.\n\nNo existe una receta universal para pasar de una versión a otra. Human, Hacker, Ghoul y otras razas pueden tener caminos distintos, y algunas razas ni siquiera usan V1→V4 como eje principal. Saiyan, por ejemplo, gira alrededor de entrenamiento y transformaciones.\n\nV4 importa porque muchos Trials y artefactos pueden pedir una raza V4 como requisito inicial. Eso no significa que todos lo hagan. Para saber cómo avanzar una raza concreta, abrí su ficha en el Atlas de Razas.",
                    "V1 is the initial stage. In many races its effects are still subtle. V2 often makes attributes or abilities more noticeable and can unlock uses V1 did not have. V3 and V4 continue progression, but their requirements depend on the race.\n\nThere is no universal recipe for moving from one version to another. Human, Hacker, Ghoul and other races can follow different paths, and some races do not use V1→V4 as their main progression at all. Saiyan, for example, revolves around training and transformations.\n\nV4 matters because many Trials and artifacts can use a V4 race as an initial requirement. That does not mean all of them do. To learn how a specific race progresses, open its Race Atlas entry.",
                    true, List.of("race-human", "race-hacker", "race-ghoul", "race-saiyan", "trials-basics"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "08/09/2026", "Progresión racial",
                            "V1 tiene pocos efectos visibles, V2 vuelve efectos y atributos más notorios y muchos Trials/artefactos usan V4 como requisito.",
                            "V1 has few visible effects, V2 makes effects and attributes more noticeable, and many Trials/artifacts use V4 as a requirement.")),

            e("trials-basics", SiegeKnowledgeData.Domain.TRIALS,
                    "Trials", "Trials",
                    "Los Trials son pruebas o lugares especiales con requisitos propios y recompensas concretas.",
                    "Trials are special challenges or locations with their own requirements and specific rewards.",
                    "No todos los Trials funcionan igual. Algunos están ligados a una raza, otros a meditación, armas, objetos o una recompensa específica. Pueden pedir nivel, una versión racial, objetos o pasos previos.\n\nEn el Atlas cada Trial conocido aparece por separado. Antes de entrar, revisá su ficha: que un Trial pida V4 o cierto nivel no significa que esa regla sirva para todos los demás.",
                    "Trials do not all work the same way. Some are tied to a race, meditation, weapons, items or a specific reward. They may require levels, a race stage, items or earlier steps.\n\nIn the Atlas each known Trial is listed separately. Check its entry before entering: a V4 or level requirement for one Trial does not automatically apply to every other Trial.",
                    true, List.of("trial-spire", "trial-meditation", "trial-race", "trial-weapons", "trial-witch", "trial-third-justice"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "14/09/2026", "Trials",
                            "Múltiples tipos de Trial aparecen de forma separada en el registro.",
                            "Multiple Trial types appear separately throughout the records.")),

            e("trial-spire", SiegeKnowledgeData.Domain.TRIALS,
                    "Trial Spire", "Trial Spire",
                    "Un Trial conocido como Spire; su interior fue descrito con NPC/jugadores interactuando.",
                    "A Trial known as Spire; its interior was described with NPC/player-like characters interacting.",
                    "Está confirmado que existe como Trial independiente. El registro disponible no deja una lista actual y completa de todos sus requisitos, por lo que la ficha no inventa un costo, nivel o ruta de acceso que no esté confirmado.",
                    "It is confirmed as a separate Trial. The available record does not provide a complete current list of all its requirements, so this entry does not invent a cost, level or access route that is not confirmed.",
                    false, List.of("trials-basics"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "17/05/2026", "Trials",
                            "Trial Spire mencionado directamente.", "Trial Spire directly mentioned.")),

            e("trial-meditation", SiegeKnowledgeData.Domain.TRIALS,
                    "Trials de meditación", "Meditation Trials",
                    "Pruebas ligadas al sistema de meditación; sus requisitos pueden depender del nivel alcanzado.",
                    "Challenges tied to meditation; requirements may depend on the level reached.",
                    "La meditación tiene progreso propio y algunos Trials aparecen alrededor de ese sistema. El registro muestra que ciertos accesos o acciones dependen del nivel de meditación, pero los valores han cambiado con el tiempo. Por eso esta ficha explica el sistema sin fijar un número viejo como si todavía fuera universal.",
                    "Meditation has its own progression and some Trials are built around that system. Records show that certain accesses or actions depend on meditation level, but those values have changed over time. This entry therefore explains the system without treating an old number as a permanent rule.",
                    false, List.of("trials-basics"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "07/09/2026", "Meditación / Trials",
                            "Los requisitos exactos de meditación han variado.", "Exact meditation requirements have varied.")),

            e("trial-race", SiegeKnowledgeData.Domain.TRIALS,
                    "Trials de raza", "Race Trials",
                    "Trials relacionados directamente con una raza o con su progresión.",
                    "Trials directly related to a race or its progression.",
                    "Pueden formar parte de la forma de obtener, mejorar o completar una ruta racial. Como cada raza puede tener pasos distintos, la ficha de la raza debe indicar qué Trial le corresponde cuando esa relación esté confirmada.",
                    "They may be part of obtaining, improving or completing a race path. Because every race can have different steps, the race entry should state which Trial applies when that link is confirmed.",
                    false, List.of("trials-basics", "race-system"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "07/07/2026", "Trials de raza",
                            "Existencia de Trials de raza confirmada.", "Race Trials confirmed to exist.")),

            e("trial-weapons", SiegeKnowledgeData.Domain.TRIALS,
                    "Trials de armas", "Weapon Trials",
                    "Pruebas asociadas a armas u objetos concretos.", "Challenges associated with specific weapons or items.",
                    "El registro incluye Trials ligados a armas, incluida una ruta de katana. No se agrupan bajo una sola receta: cada arma puede pedir pasos y condiciones diferentes.",
                    "The records include Trials tied to weapons, including a katana route. They are not grouped under one universal recipe: each weapon can require different steps and conditions.",
                    false, List.of("trials-basics"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "05/08/2026", "Trials de armas",
                            "Trials de armas mencionados en la progresión.", "Weapon Trials mentioned in progression.")),

            e("trial-witch", SiegeKnowledgeData.Domain.TRIALS,
                    "Witch Trials", "Witch Trials",
                    "Una familia de Trials conocida como Witch Trials.", "A family of Trials known as Witch Trials.",
                    "Su existencia y acceso fueron mencionados varias veces en septiembre. Los pasos exactos no quedan suficientemente claros en el registro actual como para presentarlos como una guía cerrada, así que esta ficha sirve para identificar el nombre y separarlo de otros Trials.",
                    "Their existence and access were mentioned several times in September. The exact steps are not clear enough in the current record to present them as a complete guide, so this entry identifies the name and keeps it separate from other Trials.",
                    false, List.of("trials-basics"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "14/09/2026", "Witch Trials",
                            "Witch Trials mencionados como destino activo.", "Witch Trials mentioned as an active destination.")),

            e("trial-third-justice", SiegeKnowledgeData.Domain.TRIALS,
                    "Trial de Third Justice", "Third Justice Trial",
                    "Trial asociado al escudo Third Justice y a su capacidad de parry.",
                    "Trial associated with the Third Justice shield and its parry ability.",
                    "Third Justice fue descrito como un escudo obtenido mediante su Trial. Si acertás el parry, puede rechazar con fuerza a Executores. La ficha evita copiar requisitos antiguos del Trial cuando no están confirmados como actuales.",
                    "Third Justice was described as a shield obtained through its Trial. A successful parry can knock Executors away with considerable force. This entry avoids copying old Trial requirements when they are not confirmed as current.",
                    false, List.of("trials-basics", "executors-basics"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "30/08/2026", "Third Justice",
                            "Trial y función del escudo descritos directamente.", "Trial and shield function directly described.")),

            e("executors-basics", SiegeKnowledgeData.Domain.EXECUTORS,
                    "Executores", "Executors",
                    "Amenazas especiales que conviene reconocer antes de intentar enfrentarlas como si fueran un mob normal.",
                    "Special threats worth recognizing before treating them like a normal mob.",
                    "Los Executores no son todos iguales. El subtipo importa: algunos tienen comportamientos, daño y reglas distintas, y varios pueden ignorar protecciones que normalmente esperarías conservar al morir. Los Executores de Maze tampoco deben confundirse con las criaturas normales del Maze.\n\nUna señal de cercanía puede aparecer en pantalla y algunos Executores tienen señales propias, como música o iconos. Si no sabés cuál apareció, la prioridad es identificarlo y ganar distancia antes de probar ataques. La información concreta de unidades conocidas se consulta en Intel.",
                    "Executors are not all the same. Their subtype matters: some have different behavior, damage and death rules, and several can bypass protections you would normally expect to keep. Maze Executors should not be confused with ordinary Maze creatures.\n\nA proximity warning can appear on screen and some Executors have their own cues such as music or icons. If you do not know which one appeared, identify it and create distance before testing attacks. Information on known units belongs in Intel.",
                    true, List.of("bosses-basics"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "16/09/2026", "Executores",
                            "El subtipo determina respuesta y riesgo; Executores de Maze se distinguen de criaturas del Maze.",
                            "Subtype determines response and risk; Maze Executors are distinct from ordinary Maze creatures.")),

            e("bosses-basics", SiegeKnowledgeData.Domain.BOSSES,
                    "Unidades y bosses", "Units and bosses",
                    "SIEGE tiene unidades normales, avanzadas, élites, superunidades, Executores y bosses con capacidades muy diferentes.",
                    "SIEGE has regular units, advanced units, elites, super-units, Executors and bosses with very different capabilities.",
                    "No conviene aprender una amenaza sólo por su cantidad de vida. Algunas unidades tienen ataques a distancia, instakills cercanos, telequinesis, invisibilidad, adaptación, sabotaje o efectos que cambian completamente la pelea.\n\nUsá Intel para abrir el dossier de cada unidad conocida. Ahí corresponde ver vida, origen, armamento, variantes y consejos específicos. El Briefing sólo necesita que sepas que no todo enemigo debe enfrentarse de la misma manera.",
                    "A threat should not be learned only by its health total. Some units have ranged attacks, close-range instant kills, telekinesis, invisibility, adaptation, sabotage or effects that completely change a fight.\n\nUse Intel to open the dossier of each known unit. That is where health, origin, armament, variants and specific advice belong. The Briefing only needs to make clear that not every enemy should be fought the same way.",
                    true, List.of("executors-basics"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "20/09/2026", "Unidades / Bosses",
                            "Resumen del catálogo actual de Intel.", "Summary of the current Intel catalog.")),

            e("death-revive-current", SiegeKnowledgeData.Domain.DEATH_REVIVE,
                    "Estados de heridas y reanimación", "Injury states and revival",
                    "Cuando caés, el estado importa; el sistema actual ya no usa RCP como método general de reanimación.",
                    "When you go down, the state matters; the current system no longer uses CPR as the general revival method.",
                    "El servidor puede dejar estados como Injured, Incapacitated, Dead, Mangled, Mutilated o Disfigured según lo que haya ocurrido. No todos representan la misma gravedad y algunos casos pueden requerir tratamiento especial.\n\nLa regla actual cambió: RCP dejó de ser el método general. Los desfibriladores pasaron a ser la herramienta normal para reanimar los estados de muerte del sistema actual. Si una herida concreta necesita algo adicional, se trata como excepción y no como una receta vieja aplicada a todos.\n\nSi el método cambia otra vez, esta ficha debe conservar solamente la regla más nueva conocida.",
                    "The server can apply states such as Injured, Incapacitated, Dead, Mangled, Mutilated or Disfigured depending on what happened. They do not represent the same severity and some cases may require special treatment.\n\nThe current rule changed: CPR is no longer the general method. Defibrillators became the normal tool for reviving the current death states. If a specific injury requires extra treatment, it is treated as an exception rather than applying an old recipe to everything.\n\nIf the method changes again, this entry should keep only the newest known rule.",
                    true, List.of("item-defibrillator"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "08/09/2026", "Muerte / Revive",
                            "No más RCP; desfibriladores para los estados actuales.",
                            "No more CPR; defibrillators for the current states.")),

            e("respawn-cards", SiegeKnowledgeData.Domain.DEATH_REVIVE,
                    "Reanimación actual", "Current revival",
                    "La información vieja de RCP ya no se usa como guía actual.",
                    "Old CPR information is no longer used as current guidance.",
                    "Para entender cómo funciona la reanimación ahora, consultá Estados de heridas y reanimación. Los métodos históricos quedan fuera de la guía normal para no mezclar reglas que ya cambiaron.",
                    "For the current revival system, see Injury states and revival. Historical methods are kept out of the normal guide so changed rules are not mixed together.",
                    true, List.of("death-revive-current", "item-defibrillator"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "08/09/2026", "Muerte / Revive",
                            "RCP retirado del sistema actual.", "CPR removed from the current system.")),

            e("item-defibrillator", SiegeKnowledgeData.Domain.ITEMS,
                    "Desfibrilador", "Defibrillator",
                    "Herramienta actual de reanimación para los estados de muerte de SIEGE.",
                    "Current revival tool for SIEGE death states.",
                    "Se usa para reanimar jugadores afectados por los estados de muerte del sistema actual.\n\nCrafteo actual conocido: 3 bloques de hierro + 1 mesa de encantamientos.\n\nNo se muestran recetas anteriores en esta ficha. El crafteo cambió más de una vez y la guía debe conservar únicamente el más nuevo confirmado.",
                    "Used to revive players affected by the current death-state system.\n\nLatest known recipe: 3 iron blocks + 1 enchanting table.\n\nOlder recipes are intentionally not shown here. The recipe has changed more than once and the guide keeps only the newest confirmed version.",
                    true, List.of("death-revive-current"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "22/09/2026", "Crafteos actuales",
                            "Receta actual confirmada durante la revisión 5.00.",
                            "Current recipe confirmed during the 5.00 review.")),

            e("item-geography-table", SiegeKnowledgeData.Domain.ITEMS,
                    "Geography Table", "Geography Table",
                    "Sirve para investigar información que un objeto o reliquia no muestra por sí sola.",
                    "Used to investigate information that an item or relic does not reveal on its own.",
                    "Cuando encontrás una reliquia u objeto raro y no podés ver bien qué hace, la Geography Table se usa para investigar sus propiedades y descubrir información oculta. Es una herramienta de investigación, no una mejora automática del objeto.\n\nLa ficha no muestra precios viejos ni historias de quién la compró. Si se confirma un crafteo actual, debe aparecer aquí; mientras no esté claro, se deja como desconocido.",
                    "When you find a relic or unusual item and cannot clearly see what it does, the Geography Table is used to investigate its properties and uncover hidden information. It is a research tool, not an automatic item upgrade.\n\nThis entry does not show old prices or stories about who bought it. If a current recipe is confirmed it belongs here; until then it remains unknown.",
                    false, List.of("relic-analysis-workflow", "item-daemonium-kit"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "18/09/2026", "Geography Table",
                            "Uso observado para consultar propiedades de objetos/reliquias.",
                            "Observed use for checking item/relic properties.")),

            e("item-daemonium-kit", SiegeKnowledgeData.Domain.ITEMS,
                    "Daemonium Kit", "Daemonium Kit",
                    "Herramienta usada cuando querés desarmar una reliquia o extraer materiales de ella.",
                    "Tool used when dismantling a relic or extracting materials from it.",
                    "Si querés sacar materiales de una reliquia, el Daemonium Kit forma parte del proceso. No es lo mismo que la Geography Table: la mesa sirve para investigar; el kit interviene cuando intentás desarmar o extraer componentes.\n\nManipular una reliquia a la fuerza sin el método correcto puede ser peligroso. Por eso conviene investigar primero y sólo desmontarla cuando sabés qué herramienta necesita.",
                    "If you want to extract materials from a relic, the Daemonium Kit is part of the process. It is not the same as the Geography Table: the table investigates; the kit is involved when dismantling or extracting components.\n\nForcing a relic apart without the correct method can be dangerous. Research it first and dismantle it only when you know which tool it needs.",
                    true, List.of("item-geography-table", "relic-analysis-workflow"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "19/09/2026", "Reliquias",
                            "Daemonium Kit requerido al desarmar reliquias para extraer materiales.",
                            "Daemonium Kit required when dismantling relics for materials.")),

            e("relic-analysis-workflow", SiegeKnowledgeData.Domain.RELICS,
                    "Cómo investigar una reliquia", "How to investigate a relic",
                    "Primero averiguá qué hace; después decidí si querés usarla, guardarla o extraer materiales.",
                    "Learn what it does first; then decide whether to use it, keep it or extract materials.",
                    "1. Si la información del objeto no está clara, investigalo con una Geography Table.\n\n2. No intentes desarmarlo sólo porque parece contener un material valioso. Algunas reliquias tienen un núcleo o efecto que vuelve peligroso romperlas de forma incorrecta.\n\n3. Si querés extraer materiales, usá el método indicado para esa reliquia. El Daemonium Kit aparece como herramienta necesaria para desarmar reliquias y recuperar componentes.\n\n4. Si no conocés el resultado, guardá la reliquia hasta tener más información. Esta guía evita convertir precios o pasos viejos en reglas actuales.",
                    "1. If the item's information is unclear, investigate it with a Geography Table.\n\n2. Do not dismantle it simply because it appears to contain a valuable material. Some relics have a core or effect that makes incorrect dismantling dangerous.\n\n3. If you want to extract materials, use the method indicated for that relic. The Daemonium Kit appears as a required tool for dismantling relics and recovering components.\n\n4. If the outcome is unknown, keep the relic until you have more information. This guide avoids turning old prices or steps into current rules.",
                    true, List.of("item-geography-table", "item-daemonium-kit"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "19/09/2026", "Reliquias",
                            "Separación entre investigar propiedades y extraer materiales.",
                            "Separation between researching properties and extracting materials.")),

            e("race-human", SiegeKnowledgeData.Domain.RACES,
                    "Human", "Human",
                    "Raza común con una ruta V1→V4 relativamente directa y rápida en comparación con otras.",
                    "Common race with a relatively direct and fast V1→V4 path compared with others.",
                    "Human sirve como un ejemplo sencillo de una raza que sí usa la progresión V1→V4, pero no debe tomarse como la plantilla de todas las demás. En el registro reciente fue señalada como una de las razas más rápidas de llevar hasta V4.\n\nLos requisitos exactos de cada versión deben mantenerse en la ficha sólo cuando estén confirmados como actuales.",
                    "Human is a simple example of a race that does use V1→V4 progression, but it should not be treated as the template for every other race. Recent records identify it as one of the fastest races to advance to V4.\n\nExact requirements for each version should only be kept here when confirmed as current.",
                    false, List.of("progression-v1-v4"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "08/09/2026", "Human",
                            "Human descrita como la más rápida de avanzar a V4.",
                            "Human described as the fastest to advance to V4.")),

            e("race-saiyan", SiegeKnowledgeData.Domain.RACES,
                    "Saiyan", "Saiyan",
                    "Su progreso gira alrededor del entrenamiento y las transformaciones, no de copiar una ruta V1→V4 genérica.",
                    "Its progression revolves around training and transformations rather than copying a generic V1→V4 route.",
                    "Saiyan puede crecer mucho con entrenamiento y existen máquinas o métodos que multiplican ese entrenamiento. El rendimiento depende de cuánto se haya desarrollado la raza: un Saiyan recién obtenido y uno muy entrenado no están en la misma situación.\n\nEn el registro aparecen transformaciones o variantes como Super Saiyan God, Rose Super Saiyan y Flame Saiyan. No se presentan como una lista completa ni como pasos obligatorios en ese orden; son rutas conocidas dentro de una progresión más amplia.",
                    "Saiyan can grow greatly through training, and machines or methods exist that multiply that training. Performance depends on how far the race has been developed: a newly obtained Saiyan and a heavily trained one are not equivalent.\n\nThe records mention transformations or variants such as Super Saiyan God, Rose Super Saiyan and Flame Saiyan. They are not presented as a complete list or mandatory steps in that order; they are known routes within a broader progression.",
                    true, List.of("saiyan-transformations"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "09/09/2026", "Saiyan",
                            "Entrenamiento y transformaciones descritos como eje de progreso.",
                            "Training and transformations described as the progression core.")),

            e("saiyan-transformations", SiegeKnowledgeData.Domain.PROGRESSION,
                    "Transformaciones Saiyan", "Saiyan transformations",
                    "El progreso Saiyan puede abrir transformaciones y variantes que cambian mucho su capacidad.",
                    "Saiyan progression can unlock transformations and variants that significantly change its capabilities.",
                    "Transformaciones conocidas en el registro incluyen Super Saiyan God, Rose Super Saiyan y Flame Saiyan. Flame Saiyan aparece además asociada a capacidades extremas como desatomización.\n\nNo hay suficiente información actual para afirmar que esas formas componen una única escalera lineal. La ficha las trata como transformaciones conocidas y deja los requisitos exactos separados hasta que estén confirmados.",
                    "Known transformations in the records include Super Saiyan God, Rose Super Saiyan and Flame Saiyan. Flame Saiyan is also associated with extreme capabilities such as disintegration at the atomic level.\n\nThere is not enough current information to claim these forms make up one single linear ladder. They are treated as known transformations, while exact requirements remain separate until confirmed.",
                    false, List.of("race-saiyan"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "18/09/2026", "Saiyan",
                            "Transformaciones Saiyan mencionadas en distintos momentos del registro.",
                            "Saiyan transformations mentioned at different points in the records.")),

            e("race-ghoul", SiegeKnowledgeData.Domain.RACES,
                    "Ghoul", "Ghoul",
                    "Raza con progreso propio: comer carne puede mejorarla y también existen evoluciones como V2 y Super Ghoul.",
                    "Race with its own progression: eating meat can strengthen it, and evolutions such as V2 and Super Ghoul also exist.",
                    "Ghoul no debe resumirse como una simple ruta V1→V4. El registro muestra progreso acumulado al comer carne y mejoras de habilidades asociadas a ese proceso. También aparecen V2 y Super Ghoul como evoluciones conocidas.\n\nUna ruta observada hacia V2 involucró absorber antimateria bajo una condición concreta. Eso no convierte la antimateria en una regla universal para toda evolución Ghoul. Si la progresión por carne, V2 o Super Ghoul pide una cantidad o condición exacta, la ficha sólo debe mostrarla cuando esté confirmada como actual.",
                    "Ghoul should not be reduced to a simple V1→V4 route. The records show accumulated progression from eating meat and ability improvements tied to that process. V2 and Super Ghoul also appear as known evolutions.\n\nOne observed V2 route involved absorbing antimatter under a specific condition. That does not make antimatter a universal rule for every Ghoul evolution. If meat progression, V2 or Super Ghoul requires an exact amount or condition, the entry should only show it when confirmed as current.",
                    true, List.of("ghoul-progression"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "09/09/2026", "Ghoul",
                            "Progreso por carne, V2 y Super Ghoul aparecen como rutas distintas.",
                            "Meat progression, V2 and Super Ghoul appear as distinct routes.")),

            e("ghoul-progression", SiegeKnowledgeData.Domain.PROGRESSION,
                    "Progresión Ghoul", "Ghoul progression",
                    "Comer carne forma parte de la mejora Ghoul; V2 y Super Ghoul existen como evoluciones adicionales.",
                    "Eating meat is part of Ghoul improvement; V2 and Super Ghoul exist as additional evolutions.",
                    "Se ha observado una barra/progreso relacionado con la carne y mejoras de habilidades a medida que un Ghoul se fortalece. Ciertas carnes pueden afectar ese progreso de formas distintas, por lo que no conviene asumir que cualquier carne siempre suma lo mismo.\n\nLa ruta V2 no es simplemente 'comer carne cruda': en el registro aparece separada de esa mejora y llegó a involucrar otras condiciones. Super Ghoul también existe como evolución propia. La guía mantiene estas rutas separadas para no mezclar mecanismos diferentes.",
                    "A meat-related progression bar and ability improvements have been observed as a Ghoul grows stronger. Different meat can affect that progress in different ways, so it should not be assumed that every kind of meat always adds the same amount.\n\nThe V2 route is not simply 'eat raw meat': the records distinguish it from that improvement path and show other conditions involved. Super Ghoul also exists as its own evolution. These routes remain separate so different mechanics are not mixed together.",
                    false, List.of("race-ghoul"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "09/09/2026", "Ghoul",
                            "La progresión por carne y V2 se mencionan como procesos distintos.",
                            "Meat progression and V2 are mentioned as distinct processes.")),

            e("race-subhuman", SiegeKnowledgeData.Domain.RACES,
                    "Subhuman", "Subhuman",
                    "Familia de humanos mutados con múltiples variantes; Human no representa por sí sola esta categoría.",
                    "A family of mutated humans with multiple variants; Human alone does not represent this category.",
                    "Subhuman funciona como una familia de variantes humanas mutadas. No hay que explicar toda la categoría usando una sola variante.\n\nVariantes conocidas hasta ahora: Adamantium Human, Sorcerer y Evil Morty. Cada una debe tener su propia ficha para que sus habilidades y progresión no se mezclen con las demás.",
                    "Subhuman works as a family of mutated human variants. The whole category should not be explained through one single variant.\n\nKnown variants so far include Adamantium Human, Sorcerer and Evil Morty. Each should have its own entry so their abilities and progression are not mixed together.",
                    true, List.of("subhuman-adamantium-human", "subhuman-sorcerer", "subhuman-evil-morty"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "22/07/2026", "Subhuman",
                            "Subhuman descrita como Human mutado; Adamantium Human y Sorcerer confirmados como parte de la familia.",
                            "Subhuman described as mutated Human; Adamantium Human and Sorcerer confirmed as part of the family.")),

            e("subhuman-adamantium-human", SiegeKnowledgeData.Domain.RACES,
                    "Subhuman · Adamantium Human", "Subhuman · Adamantium Human",
                    "Variante conocida de la familia Subhuman.", "Known variant of the Subhuman family.",
                    "Adamantium Human está confirmado como parte de Subhuman. El registro disponible confirma su pertenencia a la familia, pero no deja una progresión actual completa y suficientemente clara como para inventar una lista de habilidades o requisitos.\n\nCuando aparezcan pasos confirmados, deben quedar en esta ficha y no en la descripción general de Subhuman.",
                    "Adamantium Human is confirmed as part of Subhuman. The available record confirms its place in the family but does not provide a complete current progression clear enough to invent an ability or requirement list.\n\nConfirmed steps belong in this entry rather than the general Subhuman description.",
                    false, List.of("race-subhuman"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "15/07/2026", "Subhuman",
                            "Adamantium Human incluido en Subhuman.", "Adamantium Human included under Subhuman.")),

            e("subhuman-sorcerer", SiegeKnowledgeData.Domain.RACES,
                    "Subhuman · Sorcerer", "Subhuman · Sorcerer",
                    "Variante Subhuman conocida como Sorcerer.", "Subhuman variant known as Sorcerer.",
                    "Sorcerer está confirmado como una variante Subhuman y siguió apareciendo como raza activa en septiembre. La información completa de sus habilidades y requisitos todavía no queda cerrada en el registro, por lo que esta ficha no rellena esos huecos con datos de otras variantes.",
                    "Sorcerer is confirmed as a Subhuman variant and continued appearing as an active race in September. Its full ability and requirement set is not yet complete in the records, so this entry does not fill those gaps with data from other variants.",
                    false, List.of("race-subhuman"),
                    src(SiegeKnowledgeData.Confidence.STAFF_CONFIRMED, "20/09/2026", "Subhuman · Sorcerer",
                            "Sorcerer identificada como Subhuman y observada como raza activa.",
                            "Sorcerer identified as Subhuman and observed as an active race.")),

            e("subhuman-evil-morty", SiegeKnowledgeData.Domain.RACES,
                    "Subhuman · Evil Morty", "Subhuman · Evil Morty",
                    "Variante Subhuman conocida; la información detallada todavía es limitada.",
                    "Known Subhuman variant; detailed information is still limited.",
                    "Evil Morty está incluida entre las variantes Subhuman conocidas en la revisión 5.00. Todavía no hay datos suficientes para describir con seguridad sus habilidades, etapas o requisitos, así que la ficha la deja identificada sin inventar estadísticas.",
                    "Evil Morty is included among the known Subhuman variants in the 5.00 review. There is not yet enough information to safely describe its abilities, stages or requirements, so this entry identifies it without inventing statistics.",
                    false, List.of("race-subhuman"),
                    src(SiegeKnowledgeData.Confidence.SYSTEM_OBSERVED, "22/09/2026", "Subhuman · Evil Morty",
                            "Variante incluida en la revisión actual.", "Variant included in the current review."))
    );

    public static List<SiegeKnowledgeData.Entry> entries() { return ENTRIES; }
}
