package uy.santipdr.siege.client;

import net.minecraft.client.Minecraft;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.RegistryObject;
import uy.santipdr.siege.SiegeMod;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Properties;

/** Menu soundtrack controller. Never owns audio while a world/server is loaded. */
public final class SiegeMusic {
    private static final List<RegistryObject<SoundEvent>> TRACKS = List.of(
            SiegeMod.TALE_CRUEL_WORLD,
            SiegeMod.DARKEST_OF_DAYS,
            SiegeMod.KAPTAIN_MUSIC_BOX,
            SiegeMod.HEAVENS_GIFT
    );
    private static final List<String> TRACK_KEYS = List.of(
            "tale_cruel_world",
            "darkest_of_days",
            "kaptain_music_box",
            "heavens_hell_sent_gift"
    );
    private static final List<String> TRACK_NAMES = List.of(
            "Tale of a Cruel World",
            "Darkest of Days",
            "Kaptain Music Box",
            "Heaven's Hell-Sent Gift"
    );

    /**
     * Fallbacks match the complete owner uploads verified on 2026-09-09.
     * CI normally replaces these with the exact post-Vorbis values generated by
     * scripts/prepare-music.sh, so these are only used if metadata is unavailable.
     */
    private static final long[] FALLBACK_DURATIONS_MS = {
            261_534L, 281_934L, 139_969L, 217_214L
    };
    private static final long[] TRACK_DURATIONS_MS = loadDurations();
    private static final List<Integer> queue = new ArrayList<>();

    /** Natural crossfade begins exactly eight seconds before the encoded track ends. */
    private static final long NATURAL_FADE_OUT_MS = 8_000L;
    private static final long MANUAL_FADE_OUT_MS = 1_250L;
    private static final long FADE_IN_MS = 2_200L;
    private static final long ACTIVATION_GRACE_MS = 5_000L;
    public static final long TRACK_ANNOUNCEMENT_MS = 8_500L;

    private static SiegeTrackSound active;
    private static int previous = -1;
    private static long startRequestedAt;
    private static long announcementStartedAt;
    private static long playbackAnchorAt;
    private static boolean clockAnchored;
    private static float fadeGain;
    private static float fadeFromGain;
    private static long fadeStartedAt;
    private static long fadeDurationMs;
    private static boolean naturalFadeOut;
    private static FadeState fadeState = FadeState.NONE;
    private static int maintenanceTicks;

    private SiegeMusic() { }

    /** Called every client tick so vanilla menu screens keep the SIEGE soundtrack too. */
    public static void tick() {
        if (!shouldPlay()) {
            stop();
            return;
        }

        ensurePlaying();
        if (active == null) return;

        Minecraft minecraft = Minecraft.getInstance();
        var manager = minecraft.getSoundManager();
        long now = System.currentTimeMillis();

        // Anchor the duration clock only after Minecraft confirms the stream became active.
        // If the backend never reports activation, fall back after a generous grace period
        // instead of advancing early because isActive() briefly returned false.
        if (!clockAnchored) {
            if (manager.isActive(active)) {
                playbackAnchorAt = now;
                clockAnchored = true;
            } else if (now - startRequestedAt >= ACTIVATION_GRACE_MS) {
                playbackAnchorAt = startRequestedAt;
                clockAnchored = true;
            }
        }

        maintenanceTicks++;
        if (maintenanceTicks >= 100) {
            minecraft.getMusicManager().stopPlaying();
            maintenanceTicks = 0;
        }

        long elapsed = clockAnchored ? Math.max(0L, now - playbackAnchorAt) : 0L;
        long duration = currentDurationMs();

        // Never use a transient isActive(false) as the automatic-next signal. The encoded
        // duration is authoritative, so a song cannot be cut in the middle by the sound engine.
        if (clockAnchored && fadeState != FadeState.OUT && duration > 0L
                && elapsed >= Math.max(0L, duration - NATURAL_FADE_OUT_MS)) {
            beginFadeOut(NATURAL_FADE_OUT_MS, true);
        }

        if (fadeState == FadeState.IN) {
            float progress = progress(now, fadeStartedAt, fadeDurationMs);
            fadeGain = progress;
            applyLiveVolume();
            if (progress >= 1.0F) {
                fadeGain = 1.0F;
                fadeState = FadeState.NONE;
            }
        } else if (fadeState == FadeState.OUT) {
            float progress = progress(now, fadeStartedAt, fadeDurationMs);
            fadeGain = Math.max(0.0F, fadeFromGain * (1.0F - progress));
            applyLiveVolume();
            if (progress >= 1.0F || (naturalFadeOut && clockAnchored && elapsed >= duration)) {
                manager.stop(active);
                active = null;
                fadeGain = 0.0F;
                startNext(true);
            }
        } else {
            fadeGain = 1.0F;
            applyLiveVolume();
        }
    }

    public static void ensurePlaying() {
        if (!shouldPlay()) {
            stop();
            return;
        }

        if (active == null) {
            Minecraft.getInstance().getMusicManager().stopPlaying();
            maintenanceTicks = 0;
            startNext(true);
        } else {
            applyLiveVolume();
        }
    }

    /** Manual skip uses a short deliberate fade; natural transitions reserve the final eight seconds. */
    public static void nextTrack() {
        if (SiegeConfig.selectedTrack >= 0) {
            SiegeConfig.selectedTrack = (SiegeConfig.selectedTrack + 1) % TRACKS.size();
            SiegeConfig.save();
        }
        if (!SiegeConfig.music) {
            SiegeConfig.music = true;
            SiegeConfig.save();
        }
        if (!shouldPlay()) return;
        if (active == null) {
            startNext(true);
            return;
        }
        beginFadeOut(MANUAL_FADE_OUT_MS, false);
    }

    public static List<String> trackNames() { return TRACK_NAMES; }

    /** -1 resumes shuffle without restarting the currently playing track. */
    public static void selectTrack(int index) {
        if (index < -1 || index >= TRACKS.size()) return;
        SiegeConfig.selectedTrack = index;
        queue.clear();
        if (index >= 0) SiegeConfig.music = true;
        SiegeConfig.save();
        if (!shouldPlay()) return;
        if (active == null) startNext(true);
        else if (index >= 0 && (previous != index || fadeState == FadeState.OUT))
            beginFadeOut(MANUAL_FADE_OUT_MS, false);
    }

    /** Applies SIEGE's own volume to the active stream without restarting it. */
    public static void setVolumeLive(int percent) {
        SiegeConfig.musicVolume = SiegeConfig.clampVolume(percent);
        applyLiveVolume();
    }

    public static void refreshVolume() {
        applyLiveVolume();
    }

    public static String currentTrackName() {
        return previous >= 0 && previous < TRACK_NAMES.size() ? TRACK_NAMES.get(previous) : "--";
    }

    public static long trackAnnouncementAgeMs() {
        if (active == null || announcementStartedAt <= 0L) return -1L;
        long age = Math.max(0L, System.currentTimeMillis() - announcementStartedAt);
        return age <= TRACK_ANNOUNCEMENT_MS ? age : -1L;
    }

    public static boolean isActuallyPlaying() {
        return active != null;
    }

    public static long currentDurationMs() {
        if (previous < 0 || previous >= TRACK_DURATIONS_MS.length) return 0L;
        return TRACK_DURATIONS_MS[previous];
    }

    public static long currentRemainingMs() {
        if (!clockAnchored || active == null) return currentDurationMs();
        return Math.max(0L, currentDurationMs() - (System.currentTimeMillis() - playbackAnchorAt));
    }

    public static String transitionLabel(boolean spanish) {
        if (active == null) return spanish ? "ESPERANDO AUDIO" : "WAITING FOR AUDIO";
        return switch (fadeState) {
            case IN -> spanish ? "ENTRADA SUAVE" : "FADING IN";
            case OUT -> naturalFadeOut
                    ? (spanish ? "FADE FINAL · 8S" : "FINAL FADE · 8S")
                    : (spanish ? "CAMBIO SUAVE" : "FADING OUT");
            case NONE -> spanish ? "PISTA COMPLETA" : "FULL TRACK";
        };
    }

    private static boolean shouldPlay() {
        Minecraft minecraft = Minecraft.getInstance();
        return SiegeConfig.music && minecraft.level == null && minecraft.screen != null;
    }

    private static void startNext(boolean fadeIn) {
        if (!shouldPlay()) return;
        int next;
        if (SiegeConfig.selectedTrack >= 0 && SiegeConfig.selectedTrack < TRACKS.size()) {
            next = SiegeConfig.selectedTrack;
        } else {
            if (queue.isEmpty()) refillQueue();
            next = queue.remove(0);
        }
        previous = next;
        playIndex(next, fadeIn);
    }

    private static void playIndex(int index, boolean fadeIn) {
        Minecraft minecraft = Minecraft.getInstance();
        var manager = minecraft.getSoundManager();
        if (active != null) manager.stop(active);

        active = new SiegeTrackSound(TRACKS.get(index).get());
        startRequestedAt = System.currentTimeMillis();
        announcementStartedAt = startRequestedAt;
        playbackAnchorAt = startRequestedAt;
        clockAnchored = false;
        naturalFadeOut = false;
        fadeFromGain = 1.0F;
        fadeGain = fadeIn ? 0.0F : 1.0F;
        fadeState = fadeIn ? FadeState.IN : FadeState.NONE;
        fadeStartedAt = startRequestedAt;
        fadeDurationMs = fadeIn ? FADE_IN_MS : 1L;
        applyLiveVolume();
        manager.play(active);
    }

    private static void beginFadeOut(long durationMs, boolean natural) {
        if (active == null) return;
        if (fadeState == FadeState.OUT && naturalFadeOut == natural) return;
        fadeFromGain = Math.max(0.0F, Math.min(1.0F, fadeGain));
        if (fadeState == FadeState.NONE) fadeFromGain = 1.0F;
        fadeState = FadeState.OUT;
        fadeStartedAt = System.currentTimeMillis();
        fadeDurationMs = Math.max(1L, durationMs);
        naturalFadeOut = natural;
    }

    private static float progress(long now, long start, long duration) {
        if (duration <= 0L) return 1.0F;
        return Math.max(0.0F, Math.min(1.0F, (now - start) / (float) duration));
    }

    private static void applyLiveVolume() {
        if (active == null) return;
        float configured = SiegeConfig.clampVolume(SiegeConfig.musicVolume) / 100.0F;
        active.setGain(configured * Math.max(0.0F, Math.min(1.0F, fadeGain)));
    }

    private static void refillQueue() {
        queue.clear();
        for (int i = 0; i < TRACKS.size(); i++) queue.add(i);
        Collections.shuffle(queue);
        if (queue.size() > 1 && queue.get(0) == previous) Collections.swap(queue, 0, 1);
    }

    private static long[] loadDurations() {
        long[] values = FALLBACK_DURATIONS_MS.clone();
        Properties props = new Properties();
        try (InputStream in = SiegeMusic.class.getClassLoader()
                .getResourceAsStream("assets/siege/music_durations.properties")) {
            if (in == null) return values;
            props.load(in);
            for (int i = 0; i < TRACK_KEYS.size(); i++) {
                String raw = props.getProperty(TRACK_KEYS.get(i));
                if (raw == null) continue;
                long parsed = Long.parseLong(raw.trim());
                if (parsed > 1_000L) values[i] = parsed;
            }
        } catch (Exception ignored) {
            // A missing/corrupt metadata file must never crash the menu; fallbacks remain usable.
        }
        return values;
    }

    public static void stop() {
        if (active != null) Minecraft.getInstance().getSoundManager().stop(active);
        active = null;
        fadeGain = 0.0F;
        fadeFromGain = 0.0F;
        fadeState = FadeState.NONE;
        naturalFadeOut = false;
        maintenanceTicks = 0;
        announcementStartedAt = 0L;
        clockAnchored = false;
    }

    private enum FadeState { NONE, IN, OUT }
}

