package uy.santipdr.siege.client;

import java.util.List;

/**
 * Player-facing SIEGE 5.10 knowledge.
 *
 * This layer intentionally reads like an in-game guide: no research jargon,
 * no names of people, no private anecdotes and no one-player advice.
 */
public final class SiegeKnowledgePlayer510 {
    private SiegeKnowledgePlayer510() { }

    private static SiegeKnowledgeData.Entry e(String id, SiegeKnowledgeData.Domain domain,
                                               String titleEs, String titleEn,
                                               String summaryEs, String summaryEn,
                                               String bodyEs, String bodyEn,
                                               boolean critical, List<String> related) {
        return new SiegeKnowledgeData.Entry(id, SiegeKnowledgeData.Zone.SERVER, domain,
                titleEs, titleEn, summaryEs, summaryEn, bodyEs, bodyEn,
                critical, related, List.of());
    }

    private static final List<SiegeKnowledgeData.Entry> ENTRIES = List.of(
            e("server-overview", SiegeKnowledgeData.Domain.OVERVIEW,
                    "Eternal Craft — SIEGE", "Eternal Craft — SIEGE",
                    "Guerra y supervivencia en 2044 con razas, progresión, Trials, Executores, bosses, reliquias, dimensiones y sistemas propios.",
                    "War and survival in 2044 with races, progression, Trials, Executors, bosses, relics, dimensions and custom systems.",
                    "SIEGE ocurre en un mundo post-WW3 donde varias fuerzas siguen peleando por territorio, tecnología y recursos. El servidor mezcla supervivencia de Minecraft con progresión racial, habilidades, reliquias, Trials, tecnología avanzada, bosses, raids y amenazas que pueden obligarte a cambiar de plan.\n\nNo existe una sola ruta correcta para progresar. Tu raza, el equipo disponible, las zonas que explores y los sistemas que desbloquees cambian mucho lo que conviene hacer después. La Enciclopedia intenta explicar cada sistema por separado para que puedas consultar sólo lo que necesitás.",
                    "SIEGE takes place in a post-WW3 world where several forces are still fighting over territory, technology and resources. The server mixes Minecraft survival with race progression, abilities, relics, Trials, advanced technology, bosses, raids and threats that can force you to change plans.\n\nThere is no single correct progression route. Your race, available gear, explored areas and unlocked systems change what makes sense next. The Encyclopedia explains each system separately so you can open only what you need.",
                    true, List.of("race-catalog", "progression-v1-v4", "trials-basics", "executors-basics", "death-revive-current")),

            e("rarity-order", SiegeKnowledgeData.Domain.RACES,
                    "Rarezas de raza", "Race rarities",
                    "Común → Poco común → Raro → Ultra raro → Legendario → Obsainan → Mítico → Godly → Eternal → Fabled.",
                    "Common → Uncommon → Rare → Ultra Rare → Legendary → Obsainan → Mythic → Godly → Eternal → Fabled.",
                    "Ese es el orden de rarezas usado por SIEGE. Obsainan está por encima de Legendario. Algunas razas tienen una rareza conocida, como Saiyan y Deteriorer en Obsainan o Apotheosis en Eternal, mientras que otras todavía no tienen una rareza clara en la guía.\n\nLa rareza no explica por sí sola qué tan útil es una raza. También importan su progresión, habilidades, requisitos, entrenamiento y compatibilidad con otros sistemas.",
                    "This is the rarity order used by SIEGE. Obsainan is above Legendary. Some races have a known rarity, such as Saiyan and Deteriorer at Obsainan or Apotheosis at Eternal, while others still do not have a clear rarity in the guide.\n\nRarity alone does not explain how useful a race is. Progression, abilities, requirements, training and interaction with other systems matter too.",
                    false, List.of("race-catalog", "race-spins")),

            e("race-catalog", SiegeKnowledgeData.Domain.RACES,
                    "Catálogo de razas", "Race catalog",
                    "SIEGE tiene más de cincuenta razas y variantes; varias usan rutas propias en vez de una progresión universal.",
                    "SIEGE has more than fifty races and variants; several use their own routes instead of one universal progression path.",
                    "Razas y nombres registrados en SIEGE: Human, Mink, Tsufurujin, Shark, Angel, Ghoul, Cyborg, Deteriorer, Involver, Majin, Dark Manor, Hermes, Saiyan, Otsutsuki, Ackerman, Titan, Exceed, Cold Demon, Kaioshin, Dragon, Gas, Muerte, Shinigami, Fullbringer, Arrancar, Hakaishin, Zeno, Quincy, Divine, Namekian, Angel Guía, Aryano, Narehate, Arclighter, Faraón, Sun, Almirante, Archie, Emperador, Glitch Core, Jiren, Winter Hunter, Apotheosis, Lunarian, Virtud, Super Ghoul, Terrariano, Fénix, Diclonius, Windwhirl, Void Master, SOBRINO, Oni, Iluminati y Xeno Saiyan.\n\nSubhuman además tiene variantes propias, entre ellas Adamantium Human, Sorcerer, Evil Morty y Rick Sanchez. Que una raza aparezca en el catálogo no significa que todas se consigan por giros comunes ni que todas estén disponibles de la misma forma en cada etapa del servidor.",
                    "Race names used in SIEGE include Human, Mink, Tsufurujin, Shark, Angel, Ghoul, Cyborg, Deteriorer, Involver, Majin, Dark Manor, Hermes, Saiyan, Otsutsuki, Ackerman, Titan, Exceed, Cold Demon, Kaioshin, Dragon, Gas, Death, Shinigami, Fullbringer, Arrancar, Hakaishin, Zeno, Quincy, Divine, Namekian, Guide Angel, Aryano, Narehate, Arclighter, Pharaoh, Sun, Admiral, Archie, Emperor, Glitch Core, Jiren, Winter Hunter, Apotheosis, Lunarian, Virtue, Super Ghoul, Terrarian, Phoenix, Diclonius, Windwhirl, Void Master, SOBRINO, Oni, Illuminati and Xeno Saiyan.\n\nSubhuman also has its own variants, including Adamantium Human, Sorcerer, Evil Morty and Rick Sanchez. A race appearing in the catalog does not mean every race comes from common spins or is available through the same method in every server stage.",
                    false, List.of("rarity-order", "race-spins", "progression-v1-v4")),

            e("race-spins", SiegeKnowledgeData.Domain.RACES,
                    "Giros de raza", "Race spins",
                    "Los giros cambian la raza de forma aleatoria, pero no todas las razas dependen de giros comunes.",
                    "Spins change race randomly, but not every race depends on common spins.",
                    "Un giro puede darte una raza nueva o repetir una que ya salió; no garantiza subir de rareza. Algunas razas se consiguen con pasos, Trials, transformaciones o giros especiales, por lo que gastar giros comunes no sirve para buscar cualquier raza del catálogo.\n\nAntes de gastar recursos, revisá la ficha de la raza que buscás. Si la forma de obtenerla no está clara, la guía lo marca en vez de inventar un método.",
                    "A spin can give a new race or repeat a previous result; it does not guarantee a rarity upgrade. Some races are obtained through steps, Trials, transformations or special spins, so common spins cannot be used to chase every race in the catalog.\n\nBefore spending resources, check the race entry you are targeting. If its acquisition route is unclear, the guide says so instead of inventing a method.",
                    true, List.of("race-catalog", "rarity-order")),

            e("race-human", SiegeKnowledgeData.Domain.RACES,
                    "Human", "Human",
                    "Human usa V1→V4 y es una de las rutas más rápidas para llegar a V4.",
                    "Human uses V1→V4 and is one of the faster routes to V4.",
                    "La Human de SIEGE está basada en la Human de Blox Fruits y usa progresión por versiones. Su ventaja principal es que puede llegar a V4 relativamente rápido comparada con rutas más complejas. Eso puede facilitar contenido que pide V4, pero no saltea los requisitos propios de cada Trial, artefacto o evento.\n\nNo copies misiones de otros juegos como si fueran pasos de SIEGE: la ruta válida es la que funciona dentro del servidor.",
                    "SIEGE's Human is based on Blox Fruits Human and uses versioned progression. Its main advantage is reaching V4 relatively quickly compared with more complicated paths. That can help with content that requires V4, but it does not skip each Trial, artifact or event's own requirements.\n\nDo not copy quests from other games as if they were SIEGE steps: the valid route is the one that works inside the server.",
                    false, List.of("progression-v1-v4", "trials-basics")),

            e("race-shark", SiegeKnowledgeData.Domain.RACES,
                    "Shark", "Shark",
                    "Raza inspirada en Shark de Blox Fruits, con ventajas relacionadas con el agua y progresión por versiones.",
                    "Race inspired by Blox Fruits Shark, with water-related advantages and versioned progression.",
                    "Shark está relacionada con movilidad y resistencia acuática. Algunas rutas antiguas de V2 cambiaron o quedaron incompletas, así que la guía no fija una receta vieja como requisito actual.\n\nSu ventaja en agua no significa que gane automáticamente todos los enfrentamientos acuáticos: unidades tecnológicas, cyborgs y ataques especiales pueden seguir siendo peligrosos.",
                    "Shark is tied to aquatic mobility and durability. Some older V2 routes changed or remain incomplete, so the guide does not present an old recipe as a current requirement.\n\nIts water advantage does not automatically win every aquatic fight: technological units, cyborgs and special attacks can still be dangerous.",
                    false, List.of("progression-v1-v4")),

            e("race-saiyan", SiegeKnowledgeData.Domain.RACES,
                    "Saiyan / Saiyajin", "Saiyan",
                    "Raza Obsainan centrada en entrenamiento, zenkai, stats y transformaciones.",
                    "Obsainan race centered on training, zenkai, stats and transformations.",
                    "Saiyan no se entiende bien como una ruta simple V1→V4. Su progreso depende mucho del entrenamiento, el control de transformaciones, los stats y sistemas como dojos o multiplicadores. Por eso dos Saiyan pueden terminar con capacidades muy distintas aunque partan de la misma raza.\n\nEntre los nombres relacionados aparecen Flame Saiyan y Xeno Saiyan, además de transformaciones como Super Saiyan God. Los requisitos concretos de cada transformación deben consultarse por separado cuando estén claros.",
                    "Saiyan is not well represented by a simple V1→V4 path. Progress depends heavily on training, transformation control, stats and systems such as dojos or multipliers. Two Saiyans can therefore end up with very different capabilities even when they start from the same race.\n\nRelated names include Flame Saiyan and Xeno Saiyan, alongside transformations such as Super Saiyan God. Exact transformation requirements belong in their own entries when they are clear.",
                    true, List.of("dojo-training", "saiyan-transformations", "race-xeno-saiyan")),

            e("race-xeno-saiyan", SiegeKnowledgeData.Domain.RACES,
                    "Xeno Saiyan", "Xeno Saiyan",
                    "Rama Saiyan reconocida por separado dentro del catálogo.",
                    "A Saiyan branch recognized separately in the catalog.",
                    "Xeno Saiyan aparece como una raza o rama diferenciada dentro del conjunto Saiyan. La guía la separa para que no herede automáticamente todas las reglas, requisitos o transformaciones de un Saiyan normal.\n\nTodavía faltan datos claros sobre su obtención y progresión actual, así que esos campos quedan abiertos hasta que el propio servidor dé una ruta concreta.",
                    "Xeno Saiyan appears as a distinct race or branch within the Saiyan family. The guide keeps it separate so it does not automatically inherit every rule, requirement or transformation from normal Saiyan.\n\nIts current acquisition and progression route are still unclear, so those fields stay open until the server provides a concrete path.",
                    false, List.of("race-saiyan", "saiyan-transformations")),

            e("race-cyborg", SiegeKnowledgeData.Domain.RACES,
                    "Cyborg", "Cyborg",
                    "Cyborg se desarrolla mediante Assembling, implantes, trasplantes y chips.",
                    "Cyborg develops through Assembling, implants, transplants and chips.",
                    "Usar tecnología no convierte automáticamente a alguien en Cyborg. La transformación está relacionada con instalar mejoras corporales mediante Assembling, especialmente trasplantes y chips.\n\nEso hace que Cyborg tenga una progresión muy ligada a recursos y tecnología. Compatibilidad, reversibilidad y recetas concretas pueden depender de la mejora, así que cada implante debe tratarse como un objeto distinto cuando haya información suficiente.",
                    "Using technology does not automatically make someone a Cyborg. The transformation is tied to installing body upgrades through Assembling, especially transplants and chips.\n\nThat makes Cyborg progression highly dependent on resources and technology. Compatibility, reversibility and exact recipes can depend on the upgrade, so each implant should be treated separately when enough information exists.",
                    true, List.of("assembling-table")),

            e("race-ghoul", SiegeKnowledgeData.Domain.RACES,
                    "Ghoul", "Ghoul",
                    "Ghoul tiene progreso propio, alimentación con carne y evoluciones como Super Ghoul.",
                    "Ghoul has its own progression, meat-based growth and evolutions such as Super Ghoul.",
                    "Ghoul no debe confundirse con enemigos que usan el mismo nombre. Como raza, puede mejorar mediante su propia progresión y existen referencias a V2 y Super Ghoul.\n\nNo se usa una receta dudosa o vieja como requisito actual. Cuando una evolución tenga pasos claros, aparecen en su ficha correspondiente; si no, sólo se muestra lo que sí se conoce.",
                    "Ghoul should not be confused with enemies using the same name. As a race, it has its own growth path and references exist to V2 and Super Ghoul.\n\nDubious or old recipes are not treated as current requirements. When an evolution has clear steps, they belong in its own entry; otherwise the guide only shows what is actually known.",
                    false, List.of("ghoul-progression", "race-catalog")),

            e("race-subhuman", SiegeKnowledgeData.Domain.RACES,
                    "Subhuman", "Subhuman",
                    "Familia de variantes Human alteradas, cada una con reglas propias.",
                    "Family of altered Human variants, each with its own rules.",
                    "Subhuman no es una sola build. Entre sus variantes conocidas están Adamantium Human, Sorcerer, Evil Morty y Rick Sanchez. Compartir familia no significa compartir habilidades, rareza ni método de obtención.\n\nAdamantium Human se relaciona con una piel extremadamente resistente y tolerancia a radiación. Sorcerer está ligado a hechicería o energía maldita. Las otras variantes se mantienen separadas para no mezclar capacidades entre ellas.",
                    "Subhuman is not one single build. Known variants include Adamantium Human, Sorcerer, Evil Morty and Rick Sanchez. Sharing a family does not mean sharing abilities, rarity or acquisition method.\n\nAdamantium Human is associated with extremely durable skin and radiation resistance. Sorcerer is tied to sorcery or cursed energy. Other variants remain separate so abilities are not mixed between them.",
                    false, List.of("subhuman-rick-sanchez", "race-human")),

            e("progression-v1-v4", SiegeKnowledgeData.Domain.PROGRESSION,
                    "Progresión V1 → V4", "V1 → V4 progression",
                    "V1→V4 es común en varias razas, pero no es una ruta universal.",
                    "V1→V4 is common for several races, but it is not a universal route.",
                    "En las razas que usan versiones, V1 suele ser el punto inicial y V2/V3/V4 van desbloqueando o mejorando efectos. V4 aparece como requisito de varios Trials, artefactos y sistemas, pero cada raza puede pedir pasos distintos para alcanzarla.\n\nSaiyan, Cyborg y otras rutas especiales funcionan de otra manera. Antes de seguir una guía V1→V4, verificá que tu raza realmente use ese sistema.",
                    "For races that use versions, V1 is usually the starting point while V2/V3/V4 unlock or improve effects. V4 appears as a requirement for several Trials, artifacts and systems, but each race can require different steps to reach it.\n\nSaiyan, Cyborg and other special routes work differently. Before following a V1→V4 guide, make sure the race actually uses that system.",
                    true, List.of("race-catalog", "trials-basics")),

            e("trials-basics", SiegeKnowledgeData.Domain.TRIALS,
                    "Trials", "Trials",
                    "Pruebas especiales que pueden pedir raza, versión, nivel, kills, objetos u otras condiciones.",
                    "Special challenges that can require race, version, level, kills, items or other conditions.",
                    "Un Trial no es sólo una pelea. Puede tener requisitos de entrada, una condición de activación, un objetivo, castigos por fallar, tiempo limitado o una recompensa concreta. Algunos están ligados a progresión racial; otros a meditación, armas, reliquias o razas ocultas.\n\nV4 aparece como requisito en bastante contenido, pero no en todo. Si un requisito no está claro, la ficha lo marca como incompleto en vez de asumir que no existe.",
                    "A Trial is not only a fight. It can have entry requirements, an activation condition, an objective, failure penalties, a time limit or a specific reward. Some are tied to race progression; others to meditation, weapons, relics or hidden races.\n\nV4 appears as a requirement in plenty of content, but not all of it. If a requirement is unclear, the entry marks it as incomplete instead of assuming it does not exist.",
                    true, List.of("trial-shrine-global", "trial-third-justice", "progression-v1-v4")),

            e("trial-shrine-global", SiegeKnowledgeData.Domain.TRIALS,
                    "Trial del santuario", "Shrine Trial",
                    "Trial global que se inicia desde un santuario y puede involucrar objetivos repartidos por el Overworld.",
                    "Global Trial started from a shrine and able to involve objectives spread across the Overworld.",
                    "El santuario puede iniciar una prueba global con varios objetivos y una duración limitada. En distintas etapas se mencionaron kills, niveles de experiencia y coleccionables verdes por el Overworld.\n\nComo las cantidades pueden cambiar con el balance, la guía no congela números viejos. Cuando el Trial esté activo, los valores mostrados por el propio servidor son los que deben usarse.",
                    "The shrine can start a global challenge with several objectives and a limited duration. Different versions have mentioned kills, experience levels and green collectibles around the Overworld.\n\nBecause amounts can change with balancing, the guide does not freeze old numbers. When the Trial is active, use the values shown by the server itself.",
                    false, List.of("trials-basics")),

            e("trial-third-justice", SiegeKnowledgeData.Domain.TRIALS,
                    "Trial de Third Justice", "Third Justice Trial",
                    "Trial para obtener Third Justice; el último requisito concreto conocido usa 20 discos de Nightdream.",
                    "Trial used to obtain Third Justice; the latest concrete requirement known uses 20 Nightdream discs.",
                    "Third Justice está ligada a su propio Trial. El último requisito concreto conocido es reunir 20 discos de Nightdream. Como los Trials pueden cambiar, tratá esa cantidad como el dato más reciente disponible y no como una regla imposible de modificar.\n\nEl escudo tiene un parry corto y ofensivo: acertar el timing puede rechazar con mucha fuerza, incluso contra Executores. No funciona igual que simplemente mantener un escudo levantado.",
                    "Third Justice is tied to its own Trial. The latest concrete requirement known is collecting 20 Nightdream discs. Because Trials can change, treat that amount as the latest available value rather than something that can never be adjusted.\n\nThe shield has a short offensive parry: landing the timing can knock targets back very hard, including Executors. It does not work like simply holding a normal shield up.",
                    false, List.of("trials-basics", "executors-basics")),

            e("executors-basics", SiegeKnowledgeData.Domain.EXECUTORS,
                    "Executores", "Executors",
                    "Amenazas especiales con variantes, terror radius y mecánicas que cambian según el tipo.",
                    "Special threats with variants, terror radius and mechanics that change by type.",
                    "Los Executores no deben tratarse como una sola criatura con las mismas reglas. Existen variantes con comportamientos distintos y el sonido de terror radius sirve como aviso de que una amenaza de este grupo está cerca.\n\nTambién aparecen sistemas de llaves, esencias y sellos relacionados con ellos. Algunas descripciones antiguas sobre inmortalidad o cantidad total pertenecen a etapas concretas, por lo que la ficha actual evita convertirlas en reglas universales.",
                    "Executors should not be treated as one creature with identical rules. Different variants use different behaviors, and the terror radius sound warns that one of these threats is nearby.\n\nKeys, essences and seals are also connected to them. Some older descriptions about immortality or total counts belonged to specific stages, so the current entry does not turn them into universal rules.",
                    true, List.of("executor-maze", "executor-nearby-warning", "trial-third-justice")),

            e("executor-maze", SiegeKnowledgeData.Domain.EXECUTORS,
                    "Maze Executor", "Maze Executor",
                    "Variante diferenciada de Executor; no comparte automáticamente todas las reglas de otros tipos.",
                    "Distinct Executor variant; it does not automatically share every rule from other types.",
                    "Maze Executor existe como un tipo propio dentro del grupo de Executores. Su presencia es suficiente para recordar que las variantes pueden cambiar persecución, resistencia, ataques y forma de enfrentarlas.\n\nCuando un Executor tenga dossier propio, usá ese dossier antes que una descripción general del grupo.",
                    "Maze Executor exists as its own type within the Executor group. Its existence is enough to show that variants can change pursuit, durability, attacks and how they should be handled.\n\nWhen an Executor has its own dossier, use that dossier before a general description of the group.",
                    false, List.of("executors-basics")),

            e("meditation-levels", SiegeKnowledgeData.Domain.MEDITATION,
                    "Meditación", "Meditation",
                    "Sistema de entrenamiento con niveles propios que puede enfocarse en capacidades concretas.",
                    "Training system with its own levels that can focus on specific capabilities.",
                    "Meditación sirve para desarrollar capacidades y, en algunos casos, trabajar con habilidades más complejas. No es un botón que aumente automáticamente fuerza, velocidad o cualquier stat. Algunas razas pueden enfocar la meditación en una habilidad concreta, como Hacker con Room.\n\nLos niveles necesarios han cambiado más de una vez, así que cada habilidad debe mostrar su requisito actual cuando se conozca. Un número viejo no se usa como regla general.",
                    "Meditation develops capabilities and can sometimes be used for more complex abilities. It is not a button that automatically increases strength, speed or any stat. Some races can focus meditation on a specific ability, such as Hacker with Room.\n\nRequired levels have changed more than once, so each ability should show its current requirement when known. Old numbers are not used as universal rules.",
                    true, List.of("ability-room", "ability-stamina", "trials-basics")),

            e("ability-stamina", SiegeKnowledgeData.Domain.ABILITIES,
                    "Stamina de habilidades", "Ability stamina",
                    "Las habilidades consumen stamina y quedarse sin reserva puede dejarte sin respuesta.",
                    "Abilities consume stamina, and running out can leave you without a response.",
                    "La stamina forma parte del uso actual de habilidades. Al pensar una habilidad no importa sólo el efecto: también importa cuánto podés mantenerla, cuánto margen queda después y si todavía podés defenderte o escapar.\n\nNo hay un coste único para todas las habilidades. Cada una puede comportarse distinto, por lo que la ficha individual tiene prioridad cuando exista un valor concreto.",
                    "Stamina is part of the current ability system. When judging an ability, its effect is not the only thing that matters: duration, remaining reserve and whether you can still defend or escape matter too.\n\nThere is no single cost for every ability. Each one can behave differently, so the individual ability entry takes priority when a concrete value is known.",
                    false, List.of("meditation-levels", "abilities-experience")),

            e("ability-room", SiegeKnowledgeData.Domain.ABILITIES,
                    "Room", "Room",
                    "Habilidad Hacker para controlar una zona y desarrollar ese control mediante meditación.",
                    "Hacker ability for controlling an area and developing that control through meditation.",
                    "Room puede usarse para controlar accesos y defender una zona. Hacker puede entrenarla de forma enfocada mediante meditación, por lo que alcance, gasto y capacidad pueden mejorar con progresión.\n\nNo se fija un coste universal porque esos valores pueden depender del nivel y del entrenamiento. Si necesitás un número exacto, usá el que muestre la versión actual del sistema.",
                    "Room can control access and defend an area. Hacker can train it specifically through meditation, so range, cost and capability can improve with progression.\n\nThe guide does not set one universal cost because those values can depend on level and training. If you need an exact number, use the value shown by the current system.",
                    false, List.of("race-hacker", "ability-gate", "meditation-levels")),

            e("ability-gate", SiegeKnowledgeData.Domain.ABILITIES,
                    "Gate", "Gate",
                    "Habilidad Hacker de transporte a larga distancia; versiones superiores aumentan mucho su alcance.",
                    "Long-distance Hacker transport ability; higher stages greatly increase its range.",
                    "Gate conecta puntos para desplazamiento y forma parte de la progresión Hacker. En versiones altas puede cubrir distancias enormes y existen menciones de una variante mejorada llamada Rate.\n\nEl alcance exacto no se trata como fijo porque cambia con progresión y balance. La idea importante es que Gate es transporte interregional o de larga distancia, no un simple dash de combate.",
                    "Gate connects points for travel and is part of Hacker progression. At higher stages it can cover enormous distances, and an improved variant called Rate is also mentioned.\n\nExact range is not treated as fixed because it changes with progression and balance. The important point is that Gate is long-range or interregional transport, not a simple combat dash.",
                    true, List.of("race-hacker", "ability-room")),

            e("dojo-training", SiegeKnowledgeData.Domain.PROGRESSION,
                    "Dojos y entrenamiento", "Dojos and training",
                    "Los dojos multiplican entrenamiento y son especialmente útiles para Saiyan.",
                    "Dojos multiply training and are especially useful for Saiyan.",
                    "Los dojos sirven para acelerar entrenamiento. El multiplicador depende del dojo y su estado, y el sistema se relaciona con núcleos o recursos que permiten mantenerlo funcionando.\n\nSaiyan aprovecha especialmente bien este tipo de entrenamiento porque su progreso depende mucho de stats, zenkai y transformaciones. No todos los dojos deben asumirse iguales.",
                    "Dojos are used to accelerate training. The multiplier depends on the dojo and its state, and the system is tied to cores or resources that keep it working.\n\nSaiyan benefits especially well because its progression depends heavily on stats, zenkai and transformations. Do not assume every dojo uses the same multiplier.",
                    false, List.of("race-saiyan", "saiyan-transformations")),

            e("death-revive-current", SiegeKnowledgeData.Domain.DEATH_REVIVE,
                    "Heridas y reanimación", "Injuries and revival",
                    "RCP ya no es el método general; el desfibrilador es la herramienta normal para reanimar estados de muerte.",
                    "CPR is no longer the general method; the defibrillator is the normal tool for reviving death states.",
                    "SIEGE puede dejar distintos estados de heridas, como Injured, Incapacitated, Dead, Mangled, Mutilated o Disfigured. No todos significan lo mismo y algunos pueden necesitar tratamiento distinto.\n\nEl sistema actual dejó atrás la vieja escala que usaba RCP como solución general. El desfibrilador es la herramienta normal de reanimación, mientras que el Medkit se usa como objeto médico y las Respawn Cards forman una vía aparte de revive.",
                    "SIEGE can apply different injury states such as Injured, Incapacitated, Dead, Mangled, Mutilated or Disfigured. They are not equivalent and some can require different treatment.\n\nThe current system moved away from the old ladder that used CPR as the general solution. The defibrillator is the normal revival tool, the Medkit is a medical item, and Respawn Cards form a separate revival path.",
                    true, List.of("item-defibrillator", "item-medkit", "respawn-cards")),

            e("item-defibrillator", SiegeKnowledgeData.Domain.ITEMS,
                    "Desfibrilador", "Defibrillator",
                    "Herramienta normal para reanimación. Receta actual: 3 bloques de hierro + 1 bloque de oro.",
                    "Normal revival tool. Current recipe: 3 iron blocks + 1 gold block.",
                    "El desfibrilador reemplazó a RCP como método general de reanimación. Se usa para levantar estados de muerte dentro del sistema médico actual.\n\nReceta actual: 3 bloques de hierro + 1 bloque de oro. Si la receta vuelve a cambiar, la ficha debe mostrar sólo la versión vigente para no mezclar crafteos viejos.",
                    "The defibrillator replaced CPR as the general revival method. It is used to revive death states in the current medical system.\n\nCurrent recipe: 3 iron blocks + 1 gold block. If the recipe changes again, the entry should show only the current version so old crafting recipes are not mixed in.",
                    true, List.of("death-revive-current", "item-medkit")),

            e("item-medkit", SiegeKnowledgeData.Domain.ITEMS,
                    "Medkit / Botiquín", "Medkit",
                    "Objeto médico para curación. Receta actual: 3 bloques de hierro + 1 mesa de encantamientos.",
                    "Medical healing item. Current recipe: 3 iron blocks + 1 enchanting table.",
                    "El Medkit sirve para tratamiento y curación. No reemplaza al desfibrilador como herramienta general para revivir.\n\nReceta actual: 3 bloques de hierro + 1 mesa de encantamientos. Esta receta se mantiene separada de la del desfibrilador para evitar volver a mezclar ambos objetos.",
                    "The Medkit is used for treatment and healing. It does not replace the defibrillator as the general revival tool.\n\nCurrent recipe: 3 iron blocks + 1 enchanting table. This recipe stays separate from the defibrillator recipe so the two items are not mixed up again.",
                    false, List.of("death-revive-current", "item-defibrillator")),

            e("respawn-cards", SiegeKnowledgeData.Domain.DEATH_REVIVE,
                    "Respawn Cards", "Respawn Cards",
                    "Vía especial de revive separada del sistema médico; se activan con un lingote de cobre.",
                    "Special revival path separate from the medical system; activated with a copper ingot.",
                    "Una Respawn Card se activa con un lingote de cobre. Silver y Diamond Respawn Card fueron descritas como variantes que dan un revive gratis.\n\nNo son Medkits ni desfibriladores. Funcionan como un recurso especial de revive y por eso aparecen separadas en la Enciclopedia.",
                    "A Respawn Card is activated with a copper ingot. Silver and Diamond Respawn Cards were described as variants that grant a free revive.\n\nThey are not Medkits or defibrillators. They work as a special revival resource and therefore remain separate in the Encyclopedia.",
                    true, List.of("death-revive-current", "item-defibrillator")),

            e("assembling-table", SiegeKnowledgeData.Domain.ASSEMBLING,
                    "Assembling Table", "Assembling Table",
                    "Sistema de tecnología avanzada para chips, implantes, trasplantes, jetpacks y otras mejoras.",
                    "Advanced technology system for chips, implants, transplants, jetpacks and other upgrades.",
                    "Assembling no es crafteo vanilla. Se usa para tecnología avanzada y aparece conectado con reservas, jetpacks, implantes, trasplantes y chips. También es una parte importante de la ruta Cyborg.\n\nLas recetas cambian según la mejora y no todas están completas. Por eso el Atlas evita inventar materiales: una receta concreta sólo aparece cuando se conoce con suficiente claridad.",
                    "Assembling is not vanilla crafting. It is used for advanced technology and is tied to reserves, jetpacks, implants, transplants and chips. It is also an important part of the Cyborg route.\n\nRecipes vary by upgrade and are not all complete. The Atlas therefore avoids inventing materials: a concrete recipe only appears when it is clear enough.",
                    true, List.of("race-cyborg")),

            e("item-daemonium-kit", SiegeKnowledgeData.Domain.ITEMS,
                    "Daemonium Kit", "Daemonium Kit",
                    "Herramienta para recuperar materiales al desarmar reliquias.",
                    "Tool for recovering materials while dismantling relics.",
                    "El Daemonium Kit y la Geography Table hacen cosas distintas. Geography Table sirve para investigar propiedades o información oculta; Daemonium Kit se usa cuando querés extraer el material de una reliquia.\n\nPuede usarse con reliquias cuando el objetivo es recuperar sus componentes. Si no hay una receta o precio actual claro, la guía no inventa uno.",
                    "The Daemonium Kit and Geography Table do different jobs. Geography Table is used to investigate hidden properties or information; the Daemonium Kit is used when you want to extract a relic's material.\n\nIt can be used with relics when the goal is recovering their components. If there is no clear current recipe or price, the guide does not invent one.",
                    false, List.of("item-geography-table", "relic-basics")),

            e("dimensions-basics", SiegeKnowledgeData.Domain.DIMENSIONS,
                    "Dimensiones", "Dimensions",
                    "SIEGE usa varias zonas y dimensiones; algunas se conectan con razas, Trials, eventos o progresión.",
                    "SIEGE uses multiple areas and dimensions; some connect to races, Trials, events or progression.",
                    "No existe una ruta única para todas las dimensiones. Algunas aparecen ligadas a razas o eventos concretos y otras se usan como zonas de exploración o progresión.\n\nLa guía no inventa portales, objetos de entrada ni salidas cuando no están claros. A medida que una dimensión tenga una ruta bien definida, debe recibir su propia ficha con acceso, riesgos y utilidad.",
                    "There is no single route for every dimension. Some are tied to specific races or events while others are used for exploration or progression.\n\nThe guide does not invent portals, entry items or exits when they are unclear. As a dimension gets a well-defined route, it should receive its own entry with access, risks and purpose.",
                    false, List.of("server-exploration")),

            e("raids-basics", SiegeKnowledgeData.Domain.RAIDS_EVENTS,
                    "Raids y hordas", "Raids and hordes",
                    "Combates grandes que pueden mezclar oleadas, bosses, objetivos y amenazas con mecánicas distintas.",
                    "Large fights that can mix waves, bosses, objectives and threats with different mechanics.",
                    "Una raid puede cambiar mucho según el evento: algunas priorizan aguantar oleadas, otras derrotar un boss, proteger una zona o sobrevivir a varias amenazas juntas. Preparar daño, defensa, movilidad, curación y una forma de reorganizarse suele ser más útil que depender de una sola técnica.\n\nLas habilidades de área deben entenderse por lo que realmente hacen y por sus límites, no a partir de anécdotas personales de una partida concreta.",
                    "A raid can change heavily depending on the event: some focus on surviving waves, others on defeating a boss, protecting an area or surviving several threats together. Preparing damage, defense, mobility, healing and a way to regroup is usually more useful than relying on one technique.\n\nArea abilities should be understood by what they actually do and by their limits, not from personal anecdotes from one specific match.",
                    true, List.of("bosses-basics", "executors-basics"))
    );

    public static List<SiegeKnowledgeData.Entry> entries() { return ENTRIES; }
}
